# Lab Assignment 7: Database Queries
## DS 6001

### Instructions
Please answer the following questions as completely as possible using text, code, and the results of code as needed. Format your answers in a Jupyter notebook. To receive full credit, make sure you address every part of the problem, and make sure your document is formatted in a clean and professional way.

### Problem 0
Import the following packages:

In [1]:
import numpy as np
import pandas as pd
import sys
import os
import requests
import psycopg
import pymongo
import json
from bson.json_util import dumps, loads
from sqlalchemy import create_engine
import dotenv

## Problem 1
I think we teach a few subjects all wrong. The first class in statistics, for example, usually applies hypothesis testing to dumb and unrealistic examples, and involves looking-up p-values in the back of a heavy textbook. Of course this dissuades many potential statisticians from pursuing the subject. But if we instead placed the focus on probability, experimentation, and prediction and applied the methods to fun or interesting examples like games and current science, then we would make the subject much more appealing in its own right, and not just due to its associations with high income employment.

I think database work and SQL get a similarly bad treatment. 

SQL is a universal language for interacting with relational databases. MySQL, SQlite, PostgreSQL, Oracle, Microsoft, and every other relational database management system uses SQL to connect to data. SQL can be run inside Python, R, Javascript, and many other interpretive programming languages. It is the single best language for collaboration. It is far older than most programming languages yet is still in the [top 12 most frequently used languages](https://www.tiobe.com/tiobe-index/), and [30% of all data science job listings](https://365datascience.com/career-advice/data-scientist-job-market/?utm_medium=social&utm_source=web&utm_campaign=blog&utm_content=2024-job-market&utm_term=article) explicitly list SQL. But industry has done all it can to portray SQL as a barrier to entry, largely through the prevalence of SQL proficiency exams as part of data science job interview processes. The SQL exam is inescapable and scary. And every time I teach this course, I get many understandable requests for more SQL practice questions. Students want to do more SQL to pass the SQL job interview exam, but we've lost something important here: placing the emphasis on the exam misses the fact SQL is one of the very best mechanisms we have in data science for answering questions with data. If you have a database that covers a subject you care about, then you will find that SQL provides you with a working vocabulary to speak to the database as if you are speaking to a sage.

That said, many of you will be facing a SQL exam in the near future. So, you need to practice SQL. A lot. More than you can in this one homework assignment. Fortunately, there are some websites that can help you prepare with deep test banks of relevant SQL-based sample interview questions. Just keep in mind that while the examples you will see on these websites may reasonably strike you as dumb, SQL will be a lot more enjoyable if you find data that matches your interests.

### Part a
DataLemur, created by UVA alumnus Nick Singh, offers a range of SQL problems specifically designed for data science interview preparation. 

Go to https://datalemur.com/ and sign up for a free account. Then access DataLemur's collection of SQL practice interview questions: https://datalemur.com/questions?category=SQL. Complete any one question of your choice. Then copy-and-paste the text that appears when your answer is accepted. [4 points]

<strong>Accepted

Congrats 🎉 - Share this problem, and your solution, on LinkedIn or Twitter!

In your post, don’t forget to tag Nick Singh, so that he can comment on and share your post with his audience of 150k+ followers on LinkedIn and 25k+ followers on Twitter (which will give your post and profile more visibility)!

[chosen question]('https://datalemur.com/questions/time-spent-snaps')
```
SELECT age_bucket, 
  ROUND(100.0*(SUM(t_open)/(SUM(t_open)+SUM(t_send))), 2) as open_perc,
  ROUND(100.0*(SUM(t_send)/(SUM(t_open)+SUM(t_send))), 2) as send_perc
FROM (SELECT age_bucket, CASE 
    WHEN activity_type = 'open' THEN time_spent
    WHEN activity_type = 'send' THEN 0
    ELSE 0
    END AS t_open,
    CASE 
    WHEN activity_type = 'send' THEN time_spent
    WHEN activity_type = 'open' THEN 0
    ELSE 0
    END AS t_send
  FROM activities a
  JOIN age_breakdown ab ON a.user_id = ab.user_id) t_open_send
GROUP BY age_bucket
```
</strong>

### Part b
LeetCode is well-known for its extensive collection of coding challenges, including a dedicated section for SQL problems. This resource can help you practice a wide variety of SQL queries, from basic to advanced levels.

Go to https://leetcode.com/ and sign up for a free account. Then access Leetcode's collection of SQL practice interview questions: https://leetcode.com/studyplan/top-sql-50/. Correctly complete any one question of your choice. Then describe the first data visualization that appears on the page once your answer is accepted (both the type of visualization and what it means).  [4 points]

<strong>I got a histogram showing the distribution of runtimes of submitted solutions to the problem. My solution ran in 492s and beat 61.67% of solutions.

[chosen question](https://leetcode.com/problems/number-of-unique-subjects-taught-by-each-teacher/?envType=study-plan-v2&envId=top-sql-50)
```
# Write your MySQL query statement below
SELECT teacher_id, COUNT(DISTINCT subject_id) as cnt
FROM Teacher
GROUP BY teacher_id
```
</strong>

### Part c
StrataScratch offers SQL practice questions sourced from real data science interviews at big companies. 

Go to https://www.stratascratch.com and sign up for a free account. Then access StrataScratch's collection of SQL practice interview questions: https://platform.stratascratch.com/coding?code_type=1. Correctly complete any one question of your choice (but make sure there is no lock symbol next to the name, otherwise you have to pay for it, and you should NEVER give your credit card for any homework problems). Then copy-and-paste the text that appears when your answer is accepted.  [4 points]

<strong>
Execution time: 0.01616 seconds


[chosen question](https://platform.stratascratch.com/coding/10318-new-products?code_type=3)

```
SELECT company_name, SUM(year= 2020) - SUM(year = 2019) as net_products
FROM car_launches
GROUP BY company_name
```
</strong>

### Part d
When you take an SQL exam during a job interview, you will not be able to use generative AI to help you. Unless you follow the path of Roy Lee, whose start up aims to build AI mechanisms that give you answers when AI is not available via a browser or IDE. The website's [manifesto](https://cluely.com/manifesto) states plainly "We want to cheat on everything." 

Lee was especially motivated to attack this coding-exam-interview ecosystem. A recent article in New York Magazine describes Lee's motivation as follows:
> Then Lee had an idea. As a coder, he had spent some 600 miserable hours on LeetCode, a training platform that prepares coders to answer the algorithmic riddles tech companies ask job and internship candidates during interviews. Lee, like many young developers, found the riddles tedious and mostly irrelevant to the work coders might actually do on the job. What was the point? What if they built a program that hid AI from browsers during remote job interviews so that interviewees could cheat their way through instead?

Please read the New York Magazine article here: https://archive.ph/qIXd0#selection-2129.0-2138.0

Then write a short paragraph describing some of your thoughts and feelings as you read the article. There is no right or wrong answer, so be honest, whether you find yourself firmly on Roy Lee's side, on the other side, or somewhere in the middle, or if you would rather react to the anxieties professors and students express in the article regarding AI in the classroom. Use your own words, please: we care about your opinions, not your grammar. 

By the way, whatever your thoughts on the matter may be, Lee's startup just received [$5.3 million in venture capital investment](https://www.firstpost.com/tech/cheat-on-everything-suspended-from-columbia-for-ai-cheating-tool-21-year-old-now-raises-5-3m-for-startup-13882012.html).  [4 points]

<strong>

From reading this article, I get the feeling that Lee is a fundamentally uncurious person. He seems like someone who thinks he knows better than the world, and at a very basic level, I don't think that adds anything constructive. If the only goal is to *not* do things to get to the next step or make money, why should I trust you've learned anything? Why should I think you will apply such lax standards to your work at my company? 

By using AI for nearly everything, he and people who do as he does are not learning anything or fundamentally adding anything. I think Lee's claim that he was "innovating with AI" is rich because it sounds like he's using AI to stifle innovation, to help students become workers who simply reproduce existing work instead of thinking how to create something new, something original.

There are great uses for AI, but this is so not it.

The point of education, in particular, is not to get us to cut corners but to show us the complexity of the world, to make people who don't just produce output but know how and why we create. If you use AI to communicate a point, you have not learned how to articulate a point. If you use AI to write a reading response, you have not thought critically about the reading. And, by god, we need critical thinkers.

Even just for software engineers, we need people who understand what good code looks like because they've read books about it and gone through the painstaking process of writing bad code and learning why its bad. They've listened to professors and been open to learning new techniques even if they don't seem better at the start. They can look at code written by AI and critique it, which you can't do if you never have to write that code yourself.

I agree that some of the technical processes that companies put new developers through are ridiculous and gatekeep the hiring process, but I would 100% rather hire someone who failed those tests than someone who had AI solve them. Failing means you're willing to learn. Using AI just tells me you walk away from problems.

</strong>

## Problem 2

 <div style="width: 100%; overflow: hidden;">
     <div style="width: 30%; float: right;"> <img src="https://www.smbc-comics.com/comics/1433513145-20150605.png" width="300">
     
Source: [Saturday Morning Breakfast Cereal comics](https://www.smbc-comics.com/comic/shakespeare39s-big-four)

</div>
     <div style="width: 68%; float: left;"> 

As you saw on DataLemur, Leetcode, and StrataSearch, many of the practice problems regarding SQL refer to vague and general data. That does SQL and database querying in general a major disservice. I like to think about query languages as advanced question-answer engines. We ask a question, and the query combs through all the information contained in the database to get our answer. The problem with the practice problems is that the questions are not especially interesting because the data are artificial.

Now is the winter of our discontent [with SQL] Made glorious summer by this [database assignment about Shakespeare].

In lab 6, we built a database for collected works of Shakespeare.

The ER diagram to help you navigate the data is [online](https://dbdocs.io/jkropko6ce7b797cf/Shakespeare-DB?view=relationships), and here:

<img src="https://raw.githubusercontent.com/jkropko/DS-6001/refs/heads/master/localimages/Shakespeare-DB.png" width="600">

The five tables are:

**works**: One row per work authored by Shakespeare, with columns:
* `workid`: (primary key) a unique ID without spaces or special characters for the work
* `title`: the title, such as "Twelfth Night"
* `longtitle`: a longer title, if there is one, such as "Twelfth Night, Or What You Will"
* `date`: year of publication
* `genretype`: `t` is a tragedy, such as *Romeo and Juliet* and *Hamlet*; `c` is a comedy, such as *A Midsummer Night's Dream* and *As You Like It*; `h` is a history, such as *Henry V* and *Richard III*; `s` refers to Shakespeare's sonnets; `p` is a narrative (non-sonnet) poem, such as *Venus and Adonis* and *Passionate Pilgrim*
* `notes`: Column for notes from the database maintainer, currently all `NaN`
* `source`: whether the text was originally downloaded from the [Moby Project lexicon](https://en.wikipedia.org/wiki/Moby_Project) or [Project Gutenberg](https://www.gutenberg.org/). 
* `totalwords`: Total words in the work
* `totalparagraphs`: Total number of lines of dialogue for plays, or stanzas for poems

**characters**: One row per character that appears in at least one work by Shakespeare. Some characters, such as Antony or Henry IV, appear in multiple works. Columns:
* `charid`: (primary key) a unique ID for a character
* `charname`: character's name (some characters are different but have the same name, such as the First Musician in Othello and the First Musician in Romeo and Juliet). For poems, the character is "Poet" 
* `abbrev`: an abbreviation of the character's name, if needed for reference to some other analyses
* `description`: a longer description of who the character is, if available
* `speechcount`: number of lines of dialogue delivered by the character throughout the works the character appears in

**chapters**: One row for every unique scene in a play, or for every distinct poem in a collection of poems. Columns:
* `workid`: a unique ID without spaces or special characters for the work
* `chapterid`: (primary key) a unique ID for the scene/poem
* `section`: the scene/poem number
* `chapter`: the act number, if available
* `description`: short description of where the scene takes place, for plays

**paragraphs**: One row for every line of dialogue that appears in a Shakespeare play, or for every distinct poem in a collection of poems. Columns:
* `workid`: a unique ID without spaces or special characters for the work
* `paragraphid`: (primary key) a unique ID for the line of dialogue/poem
* `paragraphnum`: the position of the paragraph within the ordered list of paragraphs within a chapter
* `charid`: the unique ID of the character delivering the line of dialogue/poem
* `plaintext`: the text of the dialogue/poem
* `phonetictext`: the text of the dialogue/poem in phonetic text, useful for training computers to generate audio of this spoken text
* `stemtext`: the stems of the words in the text, useful for text analyses such as sentiment analysis
* `section`: number of the scene/poem this line appears in
* `chapter`: number of the act this line of dialogue appears in, if a play
* `charcount`: number of characters in the line
* `wordcount`: number of words in the line
* `chapterid`: unique ID for the scene/poem

**charworks**: One row for every unique combination of character and play. Most characters appear once, but some (such as Antony or Henry IV) appear multiple times. Columns
* `charid`: (primary key) unique ID for the character
* `workid`: (primary key) unique ID for the work

In this problem, we will be posing questions about Shakespeare's work that can be answered using our database, and we will use SQL to get answers to those questions.

</div>
</div>

### Part a
Launch the docker containers you used for lab 6 to run the database systems, including PostgreSQL and MongoDB. Load your PostgreSQL password from your .env file, taking care not to expose it in your code. Then use the `create_engine()` method from `sqlalchemy` to create an engine that connects to the PostgreSQL shakespeare database you saved in lab 6. Demonstrate that the connection is successful by using the `pd.read_sql_query()` method to run the following SQL code:
```
SELECT *
FROM works
```
 [4 points]

In [ ]:
dotenv.load_dotenv()

pgpassword = os.getenv("POSTGRES_PASSWORD")

dbms = 'postgresql'
package = 'psycopg'
user = 'postgres'
password = pgpassword
host = 'localhost'
port = '5432'
db = 'shakespearedb'

engine = create_engine(f'{dbms}+{package}://{user}:{password}@{host}:{port}/{db}')

In [7]:
pd.read_sql_query("SELECT * FROM works", con=engine).head()

,workid,title,longtitle,date,genretype,notes,source,totalwords,totalparagraphs
0,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031
1,allswell,All's Well That Ends Well,All's Well That Ends Well,1602,c,None,Moby,22997,1025
2,antonycleo,Antony and Cleopatra,Antony and Cleopatra,1606,t,None,Moby,24905,1344
3,asyoulikeit,As You Like It,As You Like It,1599,c,None,Gutenberg,21690,872
4,comedyerrors,Comedy of Errors,The Comedy of Errors,1589,c,None,Moby,14692,661

Now we will use the Shakespeare DB to answer some questions that come from the academic research on Shakespeare's work. The best way to write a SQL query is one step at a time, looking at the output as you go along. The first few problems will guide you through these steps, but later problems will leave the step-by-step construction of a query up to you. 

### Part b

[Lucas Erne (2013)](https://www.google.com/books/edition/Shakespeare_as_Literary_Dramatist/hppMS0sy7CQC?hl=en&gbpv=0) argues that Shakespeare wrote his plays for the stage and also for the written page, abridging the works for stage adaptation. This thesis is controversial because Shakespeare has been viewed as a playwright writing for live audiences rather than as an author writing for posterity, and Erne challenges that conception. One theory is that as Shakespeare experienced greater levels of success, he viewed himself more through the lens of his own legacy, and wrote later works in a more literary way than earlier works, producing works of greater length. 

We'll write a SQL query that examines whether early, middle, or late Shakespeare works are longer, to test this theory.

#### Step i
Write and execute a SQL query that pulls the `title` and `date` columns from the `works` table, and renames `date` to `year`.
 [4 points]

In [15]:
query = '''
SELECT title, date as year
FROM works
'''
pd.read_sql_query(query, con=engine).head()

                       title  year
0              Twelfth Night  1599
1  All's Well That Ends Well  1602
2       Antony and Cleopatra  1606
3             As You Like It  1599
4           Comedy of Errors  1589

#### Step ii
Build on the query you wrote in step (i) by using the `CASE` clause to create a new column named `era` that equals "early" when `date` is earlier than 1600, "middle" if `date` is between 1600 and 1607, and "late" if `date`is after 1607. (Note: SQL doesn't allow you to use the new name `year` instead of the old name `date` in the rest of the SQL code, unless you are using a subquery or a common table expression.)  [4 points]

In [17]:
query = '''
SELECT title, date as year,
    CASE
        WHEN date < 1600 THEN 'Early'
        WHEN date BETWEEN 1600 and 1607 THEN 'Middle'
        WHEN date > 1607 THEN 'Late'
        ELSE NULL
        END AS era
FROM works
'''
pd.read_sql_query(query, con=engine).head(10)

                       title  year     era
0              Twelfth Night  1599   Early
1  All's Well That Ends Well  1602  Middle
2       Antony and Cleopatra  1606  Middle
3             As You Like It  1599   Early
4           Comedy of Errors  1589   Early
5                 Coriolanus  1607  Middle
6                  Cymbeline  1609    Late
7                     Hamlet  1600  Middle
8           Henry IV, Part I  1597   Early
9          Henry IV, Part II  1597   Early

#### Step iii
Build on to the SQL query you wrote for step (ii) by using the `GROUP BY` clause to collapse the data to one row per value of `era`. Use the `AVG()` function to take the average of `totalwords` within each value of `era`, and rename the averaged column `average_total_words`. Also, because we don't have a way to summarize across all of the titles or publication years within each era, remove `title` and `date` from the `SELECT` clause.

Based on the output, is the hypothesis that later works have longer lengths supported, partly supported, or not supported? (Generally speaking that is, no need for a formal hypothesis test here.)  [4 points]

In [25]:
query = '''
SELECT CASE
        WHEN date < 1600 THEN 'Early'
        WHEN date BETWEEN 1600 and 1607 THEN 'Middle'
        WHEN date > 1607 THEN 'Late'
        ELSE NULL
        END AS era,
    ROUND(AVG(totalwords),0) as average_total_words
FROM works
GROUP BY era
ORDER BY average_total_words
'''
pd.read_sql_query(query, con=engine).head(10)

      era  average_total_words
0    Late              18906.0
1   Early              20329.0
2  Middle              21999.0

<strong>
Based on the output, the later works have the fewest average words, while the middle works are actually the lengthiest one avgerage. That means this hypothesis is not supported by our work.
</strong>

### Part c
[Colyvas, Egan, and Craig (2023)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0282716) argue that Shakespeare was influenced by contemporary literary trends and like his peers began using shorter speeches after 1600.  We can test these theories by using SQL to measure whether later works tend to have longer or shorter lines of dialogue than earlier works. We'll construct this query step-by-step.

#### Step i
Join the `works` table to the `paragraphs` table (an inner join is fine because there should be no works without paragraphs, and no paragraphs without a work), and keep all columns from both tables.  [4 points]

In [26]:
query = '''
SELECT * 
FROM works w
JOIN paragraphs p ON w.workid = p.workid
'''
pd.read_sql_query(query, con=engine).head(10)

,workid,title,longtitle,date,genretype,notes,source,totalwords,totalparagraphs,workid,paragraphid,paragraphnum,charid,plaintext,phonetictext,stemtext,charcount,wordcount,chapterid
0,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630863,3,xxx,"[Enter DUKE ORSINO, CURIO, and other Lords; Mu...",ENTR TK ORSN KR ANT O0R LRTS MSXNS ATNTNK,enter duke orsino curio and other lord musicia...,65.0,9.0,18704.0
1,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630864,4,ORSINO,"If music be the food of love, play on;\n[p]Giv...",IF MSK B 0 FT OF LF PL ON JF M EKSSS OF IT 0T ...,if music be the food of love plai on give me e...,646.0,114.0,18704.0
2,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630865,19,CURIO,"Will you go hunt, my lord?\n",WL Y K HNT M LRT,will you go hunt my lord,27.0,6.0,18704.0
3,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630866,20,ORSINO,"What, Curio?\n",HT KR,what curio,13.0,2.0,18704.0
4,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630867,21,CURIO,The hart.\n,0 HRT,the hart,10.0,2.0,18704.0
5,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630868,22,ORSINO,"Why, so I do, the noblest that I have:\n[p]O, ...",H S I T 0 NBLST 0T I HF O HN MN EYS TT S OLF F...,why so i do the noblest that i have o when min...,296.0,52.0,18704.0
6,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630869,30,VALENTINE-12,"So please my lord, I might not be admitted;\n[...",S PLS M LRT I MFT NT B ATMTT BT FRM HR HNTMT T...,so pleas my lord i might not be admit but from...,413.0,70.0,18704.0
7,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630870,39,ORSINO,"O, she that hath a heart of that fine frame\n[...",O X 0T H0 A HRT OF 0T FN FRM T P 0S TBT OF LF ...,o she that hath a heart of that fine frame to ...,436.0,76.0,18704.0
8,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630871,48,xxx,[Exeunt]\n,EKSNT,exeunt,9.0,1.0,18704.0
9,12night,Twelfth Night,"Twelfth Night, Or What You Will",1599,c,None,Moby,19837,1031,12night,630872,50,xxx,"[Enter VIOLA, a Captain, and Sailors]\n",ENTR FL A KPTN ANT SLRS,enter viola a captain and sailor,38.0,6.0,18705.0

#### Step ii
Build on the query you wrote in step (i) by keeping only the `title` column from the `works` table, the `plaintext` and `wordcount` columns from the `paragraphs` table, and creating a new column named `era` that is equal to "before 1600" for values of `date` before 1600, and "1600 or later" for values of `date` greater than or equal to 1600. But don't save the `date` column in the output.  [4 points]

In [29]:
query = '''
SELECT w.title, p.plaintext, p.wordcount, 
    CASE 
        WHEN date < 1600 THEN 'before 1600'
        WHEN date >= 1600 THEN '1600 or later'
        ELSE NULL
        END AS era
FROM works w
JOIN paragraphs p ON w.workid = p.workid
'''
pd.read_sql_query(query, con=engine)

,title,plaintext,wordcount,era
0,Twelfth Night,[Exit],1.0,before 1600
1,Twelfth Night,[Sings]\n[p]When that I was and a little tiny ...,124.0,before 1600
2,Twelfth Night,"[Exeunt all, except Clown]\n",4.0,before 1600
3,Twelfth Night,Pursue him and entreat him to a peace:\n[p]He ...,70.0,before 1600
4,Twelfth Night,He hath been most notoriously abused.\n,6.0,before 1600
...,...,...,...,...
35458,The Winter's Tale,"Ay, my lord; even so\n[p]As it is here set dow...",11.0,1600 or later
35459,The Winter's Tale,"Nay, that's a mock: I have seen a lady's nose\...",18.0,1600 or later
35460,The Winter's Tale,"No, no, my lord.\n",4.0,1600 or later
35461,The Winter's Tale,To satisfy your highness and the entreaties\n[...,12.0,1600 or later
35462,The Winter's Tale,Proceed:\n[p]No foot shall stir.\n,5.0,1600 or later

#### Step iii
Build off of the query you wrote for step (ii) by collapsing the data to one row per value of `era` with a column containing the average `wordcount` across paragraphs in that era. Remove any columns that cannot be meaningfully collapsed to one row per era.

Based on your result, does the evidence support the hypothesis that Shakespeare wrote shorter lines of dialogue starting in 1600? (No need for a formal hypothesis test)  [4 points]

In [31]:
query = '''
SELECT
    CASE 
        WHEN date < 1600 THEN 'before 1600'
        WHEN date >= 1600 THEN '1600 or later'
        ELSE NULL
        END AS era,
    ROUND(AVG(p.wordcount)) AS avg_wordcount
FROM works w
JOIN paragraphs p ON w.workid = p.workid
GROUP BY era
'''
pd.read_sql_query(query, con=engine)

             era  avg_wordcount
0    before 1600           26.0
1  1600 or later           24.0

<strong>
This result does support the hypothesis that Shakespeare wrote shorted speeches later in this carer because the average wordcount in or after 1600 is about 2 words shorter than it was before.
</strong>

### Part d
Shakespeare's plays were grouped into the broader genres of histories, tragedies, and comedies by a group of his colleagues for the publication of 36 of his plays in the [First Folio](https://en.wikipedia.org/wiki/First_Folio) in 1623. [Whissell (2007)](https://journals.sagepub.com/doi/abs/10.2466/pr0.101.1.177-192?casa_token=xa_qe0gK0dAAAAAA:0AXMiqTBAyLkdVdk2X8J1w7drv7nRxV34ZUfTc4c9x1u2lED-ae_s67KHg_pqAQYlbLgD-kIg7kjLA) analyzes how Shakespeare used word choice, specifically when conveying emotion and imagery, to connote genre. Specifically, Whissell finds that comedies more frequently than tragedies use words associated with "pleasantness", such as bright, kinder, rapt, satisfied, success, virtues, wise, hero, love, hope, and relief. (The full dictionary of works associated with pleasantness, activation, and imagery is [here](https://www.cs.columbia.edu/~julia/papers/dict_of_affect/DictionaryofAffect))

Write a SQL query that calculates whether each line of dialogue from every Shakespeare work contains one of these words associated with pleasantness, then calculates the proportion of total lines of dialogue from each work that contain a pleasantness word, then averages these proportions across genres to test whether there is a difference between tragedies and comedies. We will again do this together, step-by-step (though the steps are bigger ones in this problem).


#### Step i
Write a query to keep the `workid` and `plaintext` columns from the `paragraphs` table. Also, create a new column called `pleasant_line` that is equal to 1 if any of the words **bright**, **kinder**, **rapt**, **satisfied**, **success**, **virtues**, **wise**, **hero**, **love**, **hope**, or **relief** appear in the line. A few notes:

* To search for specific text such as "bright" within the `plaintext` column, use the `LIKE '%%bright%%'` syntax, as shown in [section 7.6.6. of the textbook](https://jkropko.github.io/surfing-the-data-pipeline/ch7.html#renaming-columns-and-transforming-data-values).
* The SQL text search function is case-sensitive, but we want to identify these words whether or not they are capitalized. To remove the upper-case letters from `plaintext` while searching for text, use `LOWER(plaintext) LIKE '%%bright%%'`.
* To search for multiple terms, you will have to string the search syntax for each term together with a series of `OR` clauses: `LOWER(plaintext) LIKE '%%bright%%' OR LOWER(plaintext) LIKE '%%kinder%%' OR . . .`.
* The default output of a `LIKE` clause is a logical type True/False column. To turn this column into 0s for False and 1s for True (to enable arithmetic operations later) wrap the column inside `CAST(... AS INT)` to convert it to an integer-type column. 

 [4 points]

In [56]:
words = ['bright', 'kinder', 'rapt', 'satisfied', 'success','virtues','wise','hero','love','hope', 'relief']
condition = ' OR '.join(f"LOWER(p.plaintext) LIKE '%%{word}%%'" for word in words)
query = f'''
SELECT w.workid, p.plaintext, CAST(({condition}) AS INT) AS pleasant_line
FROM works w
JOIN paragraphs p ON w.workid = p.workid
'''
print(query)
pd.read_sql_query(query, con=engine)

SELECT w.workid, p.plaintext, CAST((LOWER(p.plaintext) LIKE '%%bright%%' OR LOWER(p.plaintext) LIKE '%%kinder%%' OR LOWER(p.plaintext) LIKE '%%rapt%%' OR LOWER(p.plaintext) LIKE '%%satisfied%%' OR LOWER(p.plaintext) LIKE '%%success%%' OR LOWER(p.plaintext) LIKE '%%virtues%%' OR LOWER(p.plaintext) LIKE '%%wise%%' OR LOWER(p.plaintext) LIKE '%%hero%%' OR LOWER(p.plaintext) LIKE '%%love%%' OR LOWER(p.plaintext) LIKE '%%hope%%' OR LOWER(p.plaintext) LIKE '%%relief%%') AS INT) AS pleasant_line
FROM works w
JOIN paragraphs p ON w.workid = p.workid

,workid,plaintext,pleasant_line
0,12night,[Exit],0
1,12night,[Sings]\n[p]When that I was and a little tiny ...,0
2,12night,"[Exeunt all, except Clown]\n",0
3,12night,Pursue him and entreat him to a peace:\n[p]He ...,0
4,12night,He hath been most notoriously abused.\n,0
...,...,...,...
35458,winterstale,"Ay, my lord; even so\n[p]As it is here set dow...",0
35459,winterstale,"Nay, that's a mock: I have seen a lady's nose\...",0
35460,winterstale,"No, no, my lord.\n",0
35461,winterstale,To satisfy your highness and the entreaties\n[...,0
35462,winterstale,Proceed:\n[p]No foot shall stir.\n,0

#### Step ii
Building off of the query you wrote for part (i), collapse the data to one row per work with the average value of `pleasant_line` (the average of a column of 0s and 1s is the proportion of rows that have a 1).  [4 points]

In [60]:
words = ['bright', 'kinder', 'rapt', 'satisfied', 'success','virtues','wise','hero','love','hope', 'relief']
condition = ' OR '.join(f"LOWER(p.plaintext) LIKE '%%{word}%%'" for word in words)
query = f'''
SELECT w.workid, 
    ROUND(AVG(CAST(({condition}) AS INT)),2) AS pleasant_line_proportion
FROM works w
JOIN paragraphs p ON w.workid = p.workid
GROUP BY w.workid
'''
pd.read_sql_query(query, con=engine).head(10)

         workid  pleasant_line_proportion
0       12night                      0.08
1      allswell                      0.09
2    antonycleo                      0.05
3   asyoulikeit                      0.14
4  comedyerrors                      0.05
5    coriolanus                      0.06
6     cymbeline                      0.07
7        hamlet                      0.07
8      henry4p1                      0.05
9      henry4p2                      0.05

#### Step iii
Using a subquery as shown in [section 7.6.8 of the textbook](https://jkropko.github.io/surfing-the-data-pipeline/ch7.html#subqueries), or a common table expression as shown [here](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.geeksforgeeks.org/cte-in-sql/&ved=2ahUKEwigp4nHwY2OAxXeM2IAHTJWGCgQFnoECBoQAQ&usg=AOvVaw1zf1ktrRnnw05nM2xn6EbI), treat the output of your query from step (ii) as a new, temporary table. Join this table with the `works` table, and collapse the data to one row per genre with the average across works of the proportions you calculated in step (ii).

Based on your result, does the evidence support the hypothesis that comedies have higher use of pleasant-words than tragedies? (Again, no need for any formal hypothesis test or analysis beyond the SQL query output).

[Note: in the steps laid out in this problem, you might reasonably think we can first join the parapgraph and works tables, then create the `pleasant_line` average, so as to avoid using a subquery or a common table expression. The reason why this approach doesn't work is because we've renamed a column to `pleasant_line` from a very complicated default name, but this alias name is not understood by PostgreSQL until the query is executed, so we would have to use the complicated name when collapsing the data to genres. Instead, by using a subquery or CTE, the first part of the query is executed and saved, along with the column alias, for use in the second part of the query.]

 [8 points]

In [85]:
words = ['bright', 'kinder', 'rapt', 'satisfied', 'success','virtues','wise','hero','love','hope', 'relief']
condition = ' OR '.join(f"LOWER(p.plaintext) LIKE '%%{word}%%'" for word in words)
subquery = f'''
SELECT w.workid, 
    ROUND(AVG(CAST(({condition}) AS INT)),2) AS pleasant_line_proportion
FROM works w
JOIN paragraphs p ON w.workid = p.workid
GROUP BY w.workid
'''

query = f'''
SELECT wrks.genretype, AVG(plp.pleasant_line_proportion) AS avg_pleasant_line_proportion
FROM works wrks
JOIN ({subquery}) plp
    ON wrks.workid = plp.workid
GROUP BY wrks.genretype

'''
print(query)
res = pd.read_sql_query(query, con=engine).head(10)
res

SELECT wrks.genretype, AVG(plp.pleasant_line_proportion) AS avg_pleasant_line_proportion
FROM works wrks
JOIN (
SELECT w.workid,
    ROUND(AVG(CAST((LOWER(p.plaintext) LIKE '%%bright%%' OR LOWER(p.plaintext) LIKE '%%kinder%%' OR LOWER(p.plaintext) LIKE '%%rapt%%' OR LOWER(p.plaintext) LIKE '%%satisfied%%' OR LOWER(p.plaintext) LIKE '%%success%%' OR LOWER(p.plaintext) LIKE '%%virtues%%' OR LOWER(p.plaintext) LIKE '%%wise%%' OR LOWER(p.plaintext) LIKE '%%hero%%' OR LOWER(p.plaintext) LIKE '%%love%%' OR LOWER(p.plaintext) LIKE '%%hope%%' OR LOWER(p.plaintext) LIKE '%%relief%%') AS INT)),2) AS pleasant_line_proportion
FROM works w
JOIN paragraphs p ON w.workid = p.workid
GROUP BY w.workid
) plp
    ON wrks.workid = plp.workid
GROUP BY wrks.genretype

  genretype  avg_pleasant_line_proportion
0         c                      0.099286
1         h                      0.073333
2         p                      0.296000
3         s                      0.710000
4         t                      0.073636

<strong>In the comedies, about 10% of the lines are considered pleasant by the metric we've developed, whereas only 7% of the lines in the tragedies are pleasant. So this does support the theory!
</strong>

### Part e
[Champion (1976)](https://www.jstor.org/stable/27796535) analyzes the soliloquies in Hamlet. A soliloquoy is a speech that a character gives  in which they speak to themselves. These speeches represent a character's inner thoughts and internal monologue. In Hamlet, Champion notes that the soliloquoys represent "Hamlet's inner struggle. The devices of internalization, for example, are far more extensive than in the earlier tragedies. More important, the clue to Hamlet's personality is to be found in the quite unique manner in which the playwright utilizes these devices to reveal the complexity of this inner man."

Write a SQL query that displays the longest speech delivered by Hamlet. Then, in writing, identify part of this speech that demonstrates Hamlet's inner struggle.

This time you are on your own to take the steps you need. But please remember that the best way to write a SQL query is to take it step-by-step.

A few notes:
* In this case, `wordcount` in the paragraphs table measures the length of speeches, so use this column. But in general if we did not have this column, we could use the `LENGTH()` clause in SQL to count the number of characters in each text value.
* To see the maximum value of a column, you can sort with `ORDER BY` with the `DESC` clause, then use `LIMIT 1` to show only the first value.
* The output of `pd.read_sql_query()` is stored as a Pandas dataframe. To extract the first value of a column named `plaintext` and to print it in a readable way, you can write: `print(pd.read_sql_query(myquery, con=engine)['plaintext'][0])` in Python, outside the SQL code.

 [8 points]

In [ ]:
query = '''
SELECT wordcount, plaintext
FROM paragraphs
WHERE workid='hamlet' AND charid='hamlet'
ORDER BY wordcount DESC
LIMIT 1
'''
res = pd.read_sql_query(query, con=engine).head(10)
res
print(res['plaintext'][0])

Ay, so, God b' wi' ye!                        [Exeunt Rosencrantz and Guildenstern
[p]Now I am alone.
[p]O what a rogue and peasant slave am I!
[p]Is it not monstrous that this player here,
[p]But in a fiction, in a dream of passion,
[p]Could force his soul so to his own conceit
[p]That, from her working, all his visage wann'd,
[p]Tears in his eyes, distraction in's aspect,
[p]A broken voice, and his whole function suiting
[p]With forms to his conceit? And all for nothing!
[p]For Hecuba!
[p]What's Hecuba to him, or he to Hecuba,
[p]That he should weep for her? What would he do,
[p]Had he the motive and the cue for passion
[p]That I have? He would drown the stage with tears
[p]And cleave the general ear with horrid speech;
[p]Make mad the guilty and appal the free,
[p]Confound the ignorant, and amaze indeed
[p]The very faculties of eyes and ears.
[p]Yet I,
[p]A dull and muddy-mettled rascal, peak
[p]Like John-a-dreams, unpregnant of my cause,
[p]And can say nothing! No, not for a king,
[p]Upon whose property and most dear life
[p]A damn'd defeat was made. Am I a coward?
[p]Who calls me villain? breaks my pate across?
[p]Plucks off my beard and blows it in my face?
[p]Tweaks me by th' nose? gives me the lie i' th' throat
[p]As deep as to the lungs? Who does me this, ha?
[p]'Swounds, I should take it! for it cannot be
[p]But I am pigeon-liver'd and lack gall
[p]To make oppression bitter, or ere this
[p]I should have fatted all the region kites
[p]With this slave's offal. Bloody bawdy villain!
[p]Remorseless, treacherous, lecherous, kindless villain!
[p]O, vengeance!
[p]Why, what an ass am I! This is most brave,
[p]That I, the son of a dear father murther'd,
[p]Prompted to my revenge by heaven and hell,
[p]Must (like a whore) unpack my heart with words
[p]And fall a-cursing like a very drab,
[p]A scullion!
[p]Fie upon't! foh! About, my brain! Hum, I have heard
[p]That guilty creatures, sitting at a play,
[p]Have by the very cunning of the scene
[p]Been struck so to the soul that presently
[p]They have proclaim'd their malefactions;
[p]For murther, though it have no tongue, will speak
[p]With most miraculous organ, I'll have these Players
[p]Play something like the murther of my father
[p]Before mine uncle. I'll observe his looks;
[p]I'll tent him to the quick. If he but blench,
[p]I know my course. The spirit that I have seen
[p]May be a devil; and the devil hath power
[p]T' assume a pleasing shape; yea, and perhaps
[p]Out of my weakness and my melancholy,
[p]As he is very potent with such spirits,
[p]Abuses me to damn me. I'll have grounds
[p]More relative than this. The play's the thing
[p]Wherein I'll catch the conscience of the King. Exit.

<strong>
    
 >   What would he do, \
    Had he the motive and the cue for passion \
    That I have? He would drown the stage with tears \
    And cleave the general ear with horrid speech; \
    Make mad the guilty and appal the free, \
    Confound the ignorant, and amaze indeed \
    The very faculties of eyes and ears. \
    Yet I, \
    A dull and muddy-mettled rascal, peak \
    Like John-a-dreams, unpregnant of my cause, \
    And can say nothing! 

In this part of the speech, we hear from Hamlet how turbulent his emotions are by how he describes what he imagines the actor might do if he felt what Hamlet felt. The imagine he conjures shows how deep his sorrow, and yet, as he tells us, he cannot not act, he "can say nothing".  Like a 'John-a-dreams', he feels that he is less connected to his reality than the player is to the play.

<strong>

### Part f
[Berry (2016)](https://www.google.com/books/edition/Shakespeares_Settings_and_a_Sense_of_Pla/F-yVDwAAQBAJ?hl=en&gbpv=0) argues that Shakespeare's plays are "powerfully shaped by their sense of place." That is, the choice of setting, whether a castle or palace, or a house or a garden, sets a tone which impacts the narrative and its effect on the audience. 

Write a SQL query that generates a table with one row for each of Shakespeare's works, and two columns: the title of each work, and the count of the number of scenes in each work that take place in a castle or a palace, sorted by count in descending order.

Remember, you don't have to know the whole solution from the outset. Take it step-by-step and get closer and closer to the right answer until you have it.  [12 points]

In [133]:
query = '''
SELECT w.title, SUM(CAST((c.description LIKE '%%castle%%' OR c.description LIKE '%%palace%%') AS INT)) as in_castle_palace_count
FROM works w
JOIN chapters c ON w.workid = c.workid
GROUP BY w.title
ORDER BY in_castle_palace_count DESC
'''
res = pd.read_sql_query(query, con=engine).head(30)
res

                        title  in_castle_palace_count
0                     Macbeth                      17
1   All's Well That Ends Well                      15
2        Antony and Cleopatra                      10
3                   Cymbeline                      10
4                  Richard II                      10
5                     Othello                       9
6     Two Gentlemen of Verona                       7
7           The Winter's Tale                       6
8          Henry VI, Part III                       6
9                 Richard III                       6
10                 Henry VIII                       6
11           Henry IV, Part I                       5
12                  King John                       5
13             As You Like It                       4
14                   Pericles                       4
15       Troilus and Cressida                       4
16          Henry IV, Part II                       4
17                    Henry V                       4
18           Henry VI, Part I                       4
19          Henry VI, Part II                       3
20              Twelfth Night                       3
21           Titus Andronicus                       2
22    Midsummer Night's Dream                       2
23        Measure for Measure                       1
24           Comedy of Errors                       1
25                    Sonnets                       0
26                    Tempest                       0
27                  King Lear                       0
28        Taming of the Shrew                       0
29     Phoenix and the Turtle                       0

### Problem 3
The following file contains JSON formatted data of the official English-language translations of every constitution that was in effect in the world as of 2013:

In [134]:
const = requests.get("https://github.com/jkropko/DS-6001/raw/master/localdata/const.json")
const_json = json.loads(const.text)
pd.DataFrame.from_records(const_json)

,text,country,adopted,revised,reinstated,democracy
0,'Afghanistan 2004 Preamble \n﻿In the na...,Afghanistan,2004,NaN,NaN,0.372201
1,'Albania 1998 (rev. 2012) Preamble \nWe...,Albania,1998,2012.0,NaN,0.535111
2,'Andorra 1993 Preamble \nThe Andorran P...,Andorra,1993,NaN,NaN,NaN
3,"'Angola 2010 Preamble \nWe, the people ...",Angola,2010,NaN,NaN,0.315043
4,'Antigua and Barbuda 1981 Preamble \nWH...,Antigua and Barbuda,1981,NaN,NaN,NaN
...,...,...,...,...,...,...
140,'Uzbekistan 1992 (rev. 2011) Preamble \...,Uzbekistan,1992,2011.0,NaN,0.195932
141,'Viet Nam 1992 (rev. 2013) Preamble \nI...,Viet Nam,1992,2013.0,NaN,0.251461
142,'Yemen 1991 (rev. 2001) PART ONE. THE FOUN...,Yemen,1991,2001.0,NaN,0.125708
143,"'Zambia 1991 (rev. 2009) Preamble \nWE,...",Zambia,1991,2009.0,NaN,0.405497
144,'Zimbabwe 2013 Preamble \nWe the people...,Zimbabwe,2013,NaN,NaN,0.315359

The text of the constitutions are available from the [Wolfram Data Repository](https://datarepository.wolframcloud.com/resources/World-Constitutions). I also included scores that represent the level of democratic quality in each country as of 2016. These scores are compiled by the [Varieties of Democracy (V-Dem)](https://www.v-dem.net/) project. Higher scores indicate greater levels of democratic openness and competition.

### Part a
Connect to your local MongoDB server and create a new collection for the constitution data. Use `.delete_many({})` to remove any existing data from this collection, and insert the data in `const_json` into this collection.  [4 points]

In [160]:

mongouser = os.getenv("MONGO_INITDB_ROOT_USERNAME")
mongopassword = os.getenv("MONGO_INITDB_ROOT_PASSWORD")
host = 'localhost'
port = 27017
myclient = pymongo.MongoClient(f"mongodb://{mongouser}:{mongopassword}@{host}:{port}/")

constitutiondb = myclient['constitutiondb']
const_collection = constitutiondb["constitutions"]
const_collection.delete_many({})
const_collection.insert_many(const_json)

def mongo_query_res_to_df(res):
    return pd.DataFrame.from_records(loads(dumps(res)))

#### Part b
Use MongoDB queries to produce dataframes with the following restrictions:

* The country, adoption year, and democracy features (and not `_id`, text, revised, or reinstated) for countries with constitutions that were written after 1990 
* The country, adoption year, and democracy features (and not `_id`, text, revised, or reinstated) for countries with constitutions that were written after 1990 AND have a democracy score of less than 0.5
* The country, adoption year, and democracy features (and not `_id`, text, revised, or reinstated) for countries with constitutions that were written after 1990 OR have a democracy score of less than 0.5

 [4 points]

In [162]:
res = const_collection.find({
    'adopted': {
        '$gt': 1990
    }
}, {'country': 1, 
    'adopted': 1,
    'democracy': 1,
    '_id': 0
    })
after1990 = mongo_query_res_to_df(res)
after1990

        country  adopted  democracy
0   Afghanistan     2004   0.372201
1       Albania     1998   0.535111
2       Andorra     1993        NaN
3        Angola     2010   0.315043
4       Armenia     1995   0.393278
..          ...      ...        ...
66   Uzbekistan     1992   0.195932
67     Viet Nam     1992   0.251461
68        Yemen     1991   0.125708
69       Zambia     1991   0.405497
70     Zimbabwe     2013   0.315359

[71 rows x 3 columns]

In [165]:
res = const_collection.find({
    'adopted': {
        '$lt': 1990
    },
    'democracy': {
        '$lt': 0.5
    }
}, {'country': 1, 
    'adopted': 1,
    'democracy': 1,
    '_id': 0
    })
after1990_low = mongo_query_res_to_df(res)
after1990_low

                                    country  adopted  democracy
0                                Bangladesh     1972   0.369978
1                                  Cameroon     1972   0.363031
2                                     China     1982   0.096066
3                Iran (Islamic Republic of)     1979   0.228920
4                                    Jordan     1952   0.270614
5                                    Kuwait     1962   0.311841
6                                  Malaysia     1957   0.345091
7   Korea (Democratic People's Republic of)     1972   0.090438
8                                  Pakistan     1973   0.430273
9                          Papua New Guinea     1975   0.488884
10                                Singapore     1963   0.446464
11                                   Turkey     1982   0.341745

In [166]:
res = const_collection.find({
    '$or': [{'adopted': {
        '$lt': 1990
    }},
    {'democracy': {
        '$lt': 0.5
    }}]
}, {'country': 1, 
    'adopted': 1,
    'democracy': 1,
    '_id': 0
    })
after1990_or_low = mongo_query_res_to_df(res)
after1990_or_low

                 country  adopted  democracy
0            Afghanistan     2004   0.372201
1                 Angola     2010   0.315043
2    Antigua and Barbuda     1981        NaN
3                Armenia     1995   0.393278
4              Australia     1901   0.879540
..                   ...      ...        ...
105           Uzbekistan     1992   0.195932
106             Viet Nam     1992   0.251461
107                Yemen     1991   0.125708
108               Zambia     1991   0.405497
109             Zimbabwe     2013   0.315359

[110 rows x 3 columns]

#### Part c
According to the Varieties of Democracy project, [Hungary has become less democratic](https://www.v-dem.net/en/news/democratic-declines-hungary/) over the last few years, and can no longer be considered a democracy. Update the record for Hungary to set the democracy score at 0.4. Then query the database to extract the record for Hungary and display the data in a dataframe.  [4 points]

In [167]:
const_collection.update_one(
    {'country': 'Hungary'}, 
    {'$set': 
        {'democracy': 0.4}
    }
)

mongo_query_res_to_df(const_collection.find({'country': 'Hungary'}))

,_id,text,country,adopted,revised,reinstated,democracy
0,68f8524110b7aa0801804b16,'Hungary 2011 (rev. 2013) Preamble \nGo...,Hungary,2011,2013.0,None,0.4

#### Part d
Set the `text` field in the database as a text index. Then query the database to find all constitutions that contain the exact phrase "freedom of speech". Display the country name, adoption year, and democracy scores in a dataframe for the constitutions that match this query.  [4 points]

In [193]:
const_collection.create_index([('text', 'text')])

mongo_query_res_to_df(const_collection.find(
    {'$text': {
        '$search': '\"freedom of speech\"', 
        '$caseSensitive': False
        }
    },
    {'country': 1, 
    'adopted': 1,
    'democracy': 1,
    '_id': 0
    }
))

                                        country  adopted  democracy
0                                      Slovenia     1991   0.861380
1                                        Poland     1997   0.682208
2                                       Eritrea     1997   0.075621
3                                       Croatia     1991   0.710922
4   Macedonia (The former Yugoslav Republic of)     1991   0.510983
5                                    Kazakhstan     1995   0.262596
6                                      Zimbabwe     2013   0.315359
7                                         Kenya     2010   0.531911
8                                          Fiji     2013   0.473559
9                                       Finland     1999   0.856265
10                                      Georgia     1995   0.757486
11                                      Namibia     1990   0.745421
12                                        Spain     1978   0.834466
13                          Korea (Republic of)     1948   0.757692
14                          Antigua and Barbuda     1981        NaN
15             Saint Vincent and the Grenadines     1979        NaN
16                                     Dominica     1978        NaN
17                                    Swaziland     2005   0.136008
18                                        Ghana     1992   0.670849
19                                       Gambia     1996   0.348132
20                                         Peru     1993   0.730816
21                                       Rwanda     2003   0.274476
22                             Papua New Guinea     1975   0.488884
23                                 Sierra Leone     1991   0.564657
24                                       Belize     1981        NaN
25                                      Hungary     2011   0.400000
26                                   Seychelles     1993   0.589139
27                                        China     1982   0.096066
28                        Saint Kitts and Nevis     1983        NaN
29                                       Uganda     1995   0.338308
30                                   Bangladesh     1972   0.369978
31                                      Somalia     2012   0.177772
32                                 South Africa     1996   0.727070
33                          Trinidad and Tobago     1976   0.730927
34                                       Jordan     1952   0.270614
35                                        Samoa     1962        NaN
36                                    Sri Lanka     1978   0.647035
37                                      Liberia     1986   0.629972
38                                       Mexico     1917   0.672567
39             Lao People's Democratic Republic     1991   0.094434
40                                     Pakistan     1973   0.430273
41                                        India     1949   0.632527
42                                      Myanmar     2008   0.405772
43                                       Bhutan     2008   0.537041
44      Korea (Democratic People's Republic of)     1972   0.090438
45                                  Philippines     1987   0.567393
46                                        Tonga     1875        NaN
47                             Marshall Islands     1979        NaN
48                                       Cyprus     1960   0.810509
49                                    Singapore     1963   0.446464
50                                     Malaysia     1957   0.345091
51                     United States of America     1789   0.849155

#### Part e
Use a query to search for the terms "freedom", "liberty", "legal", "justice", and "rights". Generate a text score for all of the countries, and display the data for the countries with the top 10 relevancy scores in a dataframe.  [4 points]

In [190]:
const_collection.create_index([('text', 'text')])

cur = const_collection.find(
    {'$text': {
        '$search': 'freedom liberty legal justice rights', 
        '$caseSensitive': False
        }
    },
    {'score': {'$meta': 'textScore'},
    '_id': 0
    },
    limit=10
)

mongo_query_res_to_df(cur.sort([('score', {'$meta': 'textScore'})]))

,text,country,adopted,revised,reinstated,democracy,score
0,'Serbia 2006 Preamble \nConsidering the...,Serbia,2006,NaN,None,0.474443,5.030999
1,'Finland 1999 (rev. 2011) Chapter 1. Funda...,Finland,1999,2011.0,None,0.856265,5.029000
2,'Estonia 1992 (rev. 2011) Preamble \nWi...,Estonia,1992,2011.0,None,0.909233,5.024473
3,'Armenia 1995 (rev. 2005) Preamble \nTh...,Armenia,1995,2005.0,None,0.393278,5.023651
4,'Albania 1998 (rev. 2012) Preamble \nWe...,Albania,1998,2012.0,None,0.535111,5.023087
5,"'Dominican Republic 2015 Preamble \nWe,...",Dominican Republic,2015,NaN,None,0.583654,5.019910
6,'Moldova (Republic of) 1994 (rev. 2006) Pr...,Moldova (Republic of),1994,2006.0,None,0.571357,5.017063
7,'El Salvador 1983 (rev. 2014) TITLE I ...,El Salvador,1983,2014.0,None,0.661989,5.016899
8,'Georgia 1995 (rev. 2013) Preamble \nWe...,Georgia,1995,2013.0,None,0.757486,5.015282
9,'Turkey 1982 (rev. 2011) Preamble \nAff...,Turkey,1982,2011.0,None,0.341745,5.014672

## Question 4
Once you are finished working with databases, clear up the space on your computer by going to the terminal that you used to launch the Docker containers, press CONTROL + C on your keyboard to stop the containers, then type `docker compose down` to disconnect the volumes and networks. It's a good idea to make a practice out of doing these steps when you finish working with databases.

This problem isn't graded, and no need to write anything. But please do this anyway.