# Lab Assignment 3: How to Load, Convert, and Write JSON Files in Python
## DS 6001

## Problem 0
Make sure the virtual environment you created for this course is loaded as the notebooks kernel, and load the following packages:

In [1]:
import numpy as np
import pandas as pd
import requests
import json

## Problem 1 
JSON and CSV are both text-based formats for the storage of data. It's possible to open either one in a plain text editor. Given this similarity, why does a CSV file usually take less memory than a JSON formatted file for the same data? Under what conditions could a JSON file be smaller in memory than a CSV file for the same data? [10 points]

<strong>JSON formatted files require more extra characters than a CSV file to store data. For example, say we were storing data on 3 students in a CSV. We'd have:</strong>

    fame,lname,major,grad_year\
    Cecelia,Auerswald,Engineering,2017\
    John,Doe,Bioengineering,2017\
    Jane,Doe,Literature,2016

<strong>In a JSON file, it would look like:  </strong>

    [
        {
            "fname": "Cecelia",
            "lname": "Auerswald",
            "major": "Engineering",
            "grad_year": 2017
        },
        {
            "fname": "John",
            "lname": "Doe",
            "major": "Biongineering",
            "grad_year": 2017
        },
        {
            "fname": "Jane",
            "lname": "Doe",
            "major": "Literature",
            "grad_year": 2016
        }
    ]

<strong>Other than the data, the CSV file only has commas, whereas the JSON file has to store quotation marks, curly braces, braces, etc. 
</strong>

## Problem 2
A [User-Agent header](https://en.wikipedia.org/wiki/User-Agent_header) (also called a user-agent string) is text that identifies the software you are using to access data from a web-server. It is considered to be good etiquette to write your user-agent string and send it to a web server along with your data request, and some web servers will enforce that by refusing to send you data unless you provide a user-agent string. 

Like a lot of things in software, there are stringent conventions that people follow when it comes to user-agent strings, and to operate in this world, you need to know how to abide by these conventions. 

One shortcut I recommend for writing a user-agent string in the correct format is to use an external tool. The website https://httpbin.org/user-agent examines the software you are using to access this website and mirrors back to you your user-agent string in the preferred format, in JSON format.

### Part a
Use your browser (Chrome, Firefox, Safari, etc.) to view the content at https://httpbin.org/user-agent. Copy the user-agent string and paste it here. Then identify the parts of this user-agent string that identify your web browser and your computer's operating system (Mac, Windows, etc.) [6 points]

    {
        user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
    }

**computer's OS:**  \
<strong> *(Macintosh; Intel Mac OS X 10_15_7)*</strong>  
**web browser:**\
<strong>*Chrome/140.0.0.0*</strong>

### Part b
In part (a) you found your user-agent string for situations in which you use your web browser to access data on the web, but that user-agent string would be different if you access the same web server using Python. Use the `requests.get()` method to connect to https://httpbin.org/user-agent, then display the JSON formatted response. [6 points]

In [2]:
res = requests.get("https://httpbin.org/user-agent")
res_json = json.loads( res.text)
res_json

{'user-agent': 'python-requests/2.32.3'}

<strong>The user agent is 'python-requests/2.32.3'.</strong>

### Part c
Extract the user-agent string from the output in part (b). Then create a Python dictionary, save it as a Python variable named `myheaders`, and create a key inside this dictionary called `'User-Agent'` set equal to your user-agent string. (You will use `myheaders` in the rest of the problems in this assignment.) [6 points]

In [3]:
user_agent = res_json["user-agent"]
myheaders = {}
myheaders['User-Agent'] = user_agent

### Part d
There is a huge industry built around the central task of pulling data off of websites. Most of this work is automated using specially-built software. Some software has been explicitly identified and banned from accessing certain websites due to misuse of the data or creating too much traffic for the web server to handle.

Websites often include a `robots.txt` file that lists the rules the web server asks users to follow, and publicizes the steps they've taken to restrict access. These files will sometimes call out specific user-agents. In the syntax of a `robots.txt` file, the phrase `Disallow: /` means "disallow this user from accessing anything on this website."

The following websites have `robots.txt` files that ban specific user-agents:

* https://www.tiktok.com/robots.txt
* https://www.espn.com/robots.txt
* https://www.nytimes.com/robots.txt
* https://www.amazon.com/robots.txt
* https://www.cvilletomorrow.org/robots.txt (You should check out https://www.cvilletomorrow.org/, an awesome local online newspaper with award-winning data journalism)

Choose one of these websites and find the specific user-agents that have been banned from access (user agents that have been named explicity, not `User-Agent: *` which applies to all user agents), and copy-and-paste that part of the `robots.txt` file here. Then do an internet search for one of these agents. Based on what you learn about the user-agent in question, why might you speculate that this user-agent was banned? (Any thoughtful answer to this part receives full credit). [6 points]

<strong>ESPN has disallowed the following user-agents:</strong>


    User-agent: claritybot
    Disallow: /

    User-agent: GPTBot
    Disallow: /

    User-agent: Google-Extended
    Disallow: /

    User-agent: CCBot
    Disallow: /

    User-agent: ChatGPT-User
    Disallow: /

    User-agent: anthropic-ai
    Disallow: /

    User-agent: Omgilibot
    Disallow: /

    User-agent: Omgili
    Disallow: /

    User-agent: FacebookBot
    Disallow: /

    User-agent: Bytespider
    Disallow: /

<strong>I looked up Omgili / Omgilibot. This is a web scraping bot used by Webz.io that scrapes the web for data, primarily but not exclusively user-generated content. It keeps a constantly updated repository of data to sell to other companies, including AI companies. ESPN probably does not want other companies scraping and profiting off of its web content, nor do they want anyone using ESPN content to train their LLMs and potentially profit off of it that way. </strong>

<strong>An additional reason might be that Omiglibot seems to prefer websites with frequently updating content. If omiglibot is frequently scraping your site, it could create increased artificual server load. </strong>

<strong>(Webz.com of course tells you the bot "helps send web traffic to your sites" -- helpful!)</strong>

## Problem 3 
The NBA has saved data on all 30 teams' shooting statistics for the 2014-2015 season here: https://stats.nba.com/js/data/sportvu/2015/shootingTeamData.json. Take a moment and look at this JSON file in your web browser or with https://jsonhero.io. The structure of this particular JSON is complicated, but see if you can find the team-by-team data. In this problem our goal is to use `pd.json_normalize()` to get the data into a dataframe. The following questions will guide you towards this goal.

### Part a
Download the raw text of the NBA JSON file using `requests.get()`, and provide your user-agent to the NBA API by setting the `header` argument to the `myheaders` dictionary you created in problem 2. Then use `json.loads()` (or the `.json` attribute of the `requests` output) to parse the dictionaries and lists in the JSON formatted data. [8 points]

In [15]:
res = requests.get("https://stats.nba.com/js/data/sportvu/2015/shootingTeamData.json", headers=myheaders)
json_data = json.loads(res.text)

### Part b
Based on your observations of the JSON structure, describe in words the path that leads to the team-by-team data. [8 points]

<strong> To get to the team by team data, you look at the value of the "resultSets" key in the JSON. This is a list with one element, so grab that first element (index: 0). That element is a dictionary containgin a title for the dataset, a list of column names, and lastly, stored in the key "rowSet", the data! Once you get the value for that list, you have a list of lists of data, one list per row. 

    json_data["resultSets"][0]["rowSet"]

<strong>

### Part c
Use the `pd.json_normalize()` method to pull the team-by-team data into a dataframe. 

[Note: what makes this tricky is that one of the layers in the path to the data is named only `0`. This `0` is not a string like the other keys.  Specifying `0` in the `record_path`, either with or without quotes yields an error. There are two ways to solve this. The easiest way is to just skip over the `0` key entirely when writing down the `record_path`, and `pd.json_normalize()` will include the `0` layer on its own as a default behavior. The other way is to index the JSON data with both `['resultSets'][0]` first before passing the data to `pd.json_normalize()`, then writing the remaining layers in `record_path`]

If you are successful, you will have a dataframe with 30 rows and 33 columns. The first row will refer to the Golden State Warriors, the second row will refer to the San Antonio Spurs, and the third row will refer to the Cleveland Cavaliers. The columns will only be named 0, 1, 2, ... at this point. [10 points]

In [5]:
shooting_df = pd.json_normalize(json_data, record_path=["resultSets", "rowSet"])
shooting_df

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,1610612744,Golden State,Warriors,GSW,,82,48.7,114.9,14.9,0.498,...,0.478,21.2,42.5,0.497,2.3,6.3,0.363,10.8,25.3,0.429
1,1610612759,San Antonio,Spurs,SAS,,82,48.3,103.5,14.8,0.481,...,0.506,18.3,39.8,0.460,0.9,2.6,0.341,6.1,15.9,0.381
2,1610612739,Cleveland,Cavaliers,CLE,,82,48.7,104.3,16.9,0.481,...,0.473,18.2,40.7,0.447,1.7,5.7,0.299,9.0,23.9,0.378
3,1610612746,Los Angeles,Clippers,LAC,,82,48.6,104.5,15.0,0.497,...,0.480,18.9,42.0,0.450,2.0,6.0,0.334,7.7,20.8,0.373
4,1610612760,Oklahoma City,Thunder,OKC,,82,48.6,110.2,16.1,0.480,...,0.497,17.5,38.7,0.451,1.6,5.1,0.321,6.6,18.6,0.356
5,1610612737,Atlanta,Hawks,ATL,,82,48.6,102.8,19.0,0.463,...,0.483,19.4,44.6,0.435,1.0,3.1,0.311,9.0,25.3,0.355
6,1610612745,Houston,Rockets,HOU,,82,48.6,106.5,17.2,0.433,...,0.472,15.5,36.4,0.426,2.3,7.4,0.318,8.4,23.5,0.355
7,1610612757,Portland,Trail Blazers,POR,,82,48.5,105.1,17.5,0.441,...,0.447,18.0,39.8,0.453,1.7,5.9,0.295,8.8,22.6,0.389
8,1610612758,Sacramento,Kings,SAC,,81,48.4,106.7,18.7,0.452,...,0.473,18.1,39.7,0.454,0.9,3.1,0.276,7.2,19.4,0.372
9,1610612764,Washington,Wizards,WAS,,82,48.5,104.1,15.4,0.480,...,0.483,19.5,44.3,0.439,0.7,2.7,0.254,8.0,21.5,0.371
10,1610612748,Miami,Heat,MIA,,82,48.6,100.0,17.9,0.488,...,0.490,15.7,35.2,0.445,0.8,2.9,0.282,5.3,15.1,0.347
11,1610612761,Toronto,Raptors,TOR,,81,48.5,102.7,23.0,0.462,...,0.461,14.1,32.4,0.436,1.8,5.6,0.327,6.8,17.7,0.384
12,1610612742,Dallas,Mavericks,DAL,,82,49.0,102.3,18.2,0.473,...,0.464,17.5,41.4,0.423,1.4,5.3,0.273,8.4,23.3,0.360
13,1610612766,Charlotte,Hornets,CHA,,82,48.6,103.4,16.8,0.459,...,0.449,17.0,39.8,0.427,1.8,6.0,0.297,8.9,23.4,0.379
14,1610612762,Utah,Jazz,UTA,,82,49.0,97.7,18.1,0.445,...,0.468,15.9,37.2,0.426,1.4,4.3,0.318,7.1,19.5,0.363
15,1610612753,Orlando,Magic,ORL,,81,48.7,102.0,18.0,0.456,...,0.475,18.5,42.6,0.435,0.7,2.7,0.249,7.1,19.5,0.363
16,1610612749,Milwaukee,Bucks,MIL,,82,48.7,99.0,17.4,0.463,...,0.477,13.2,29.4,0.448,1.1,4.0,0.270,4.3,11.6,0.370
17,1610612740,New Orleans,Pelicans,NOP,,82,48.5,102.7,19.9,0.458,...,0.460,17.9,41.1,0.434,0.6,2.6,0.247,7.9,21.2,0.374
18,1610612750,Minnesota,Timberwolves,MIN,,82,48.6,102.4,15.1,0.464,...,0.471,16.1,35.4,0.455,0.7,2.6,0.272,4.8,13.8,0.350
19,1610612754,Indiana,Pacers,IND,,82,48.8,102.2,13.7,0.453,...,0.465,16.4,38.1,0.431,1.7,5.7,0.299,6.4,17.4,0.368
20,1610612751,Brooklyn,Nets,BKN,,82,48.4,98.6,14.4,0.457,...,0.464,15.8,36.1,0.438,1.0,3.3,0.303,5.5,15.1,0.363
21,1610612765,Detroit,Pistons,DET,,82,48.7,102.0,17.5,0.464,...,0.452,15.7,37.2,0.422,0.9,4.0,0.227,8.1,22.2,0.366
22,1610612743,Denver,Nuggets,DEN,,82,48.6,101.9,15.9,0.406,...,0.448,16.4,37.8,0.434,1.1,4.3,0.264,6.9,19.5,0.354
23,1610612738,Boston,Celtics,BOS,,81,48.5,105.6,18.9,0.453,...,0.451,16.9,39.9,0.424,1.6,5.7,0.274,7.1,20.3,0.350
24,1610612741,Chicago,Bulls,CHI,,82,48.9,101.6,18.1,0.458,...,0.442,17.0,38.5,0.441,1.3,3.9,0.332,6.6,17.5,0.380
25,1610612755,Philadelphia,76ers,PHI,,82,48.6,97.4,19.7,0.445,...,0.449,15.3,37.4,0.409,1.6,5.7,0.281,7.7,21.8,0.354
26,1610612756,Phoenix,Suns,PHX,,82,48.4,100.9,15.6,0.440,...,0.447,16.6,39.5,0.421,1.4,5.0,0.288,7.6,20.8,0.363
27,1610612752,New York,Knicks,NYK,,82,48.5,98.4,10.4,0.447,...,0.439,15.9,36.4,0.438,1.5,4.9,0.305,5.9,16.6,0.358
28,1610612763,Memphis,Grizzlies,MEM,,82,48.6,99.1,16.4,0.440,...,0.459,16.1,38.5,0.418,0.7,2.5,0.278,5.4,16.0,0.340
29,1610612747,Los Angeles,Lakers,LAL,,82,48.3,97.3,15.6,0.441,...,0.420,14.0,34.5,0.406,2.2,7.9,0.278,5.6,16.7,0.335

### Part d
Find the path that leads to the headers (the column names), and extract these names as a list. Then set the `.columns` attribute of the dataframe you created in part c equal to this list. The result should be that the dataframe now has the correct column names.

[Note: In this case, there's no need for `pd.json_normalize()` as the headers already exist as a list.]

[8 points]

In [6]:
shooting_df.columns = json_data["resultSets"][0]["headers"]
shooting_df

,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,GP,MIN,PTS,PTS_DRIVE,FGP_DRIVE,...,CFGP,UFGM,UFGA,UFGP,CFG3M,CFG3A,CFG3P,UFG3M,UFG3A,UFG3P
0,1610612744,Golden State,Warriors,GSW,,82,48.7,114.9,14.9,0.498,...,0.478,21.2,42.5,0.497,2.3,6.3,0.363,10.8,25.3,0.429
1,1610612759,San Antonio,Spurs,SAS,,82,48.3,103.5,14.8,0.481,...,0.506,18.3,39.8,0.460,0.9,2.6,0.341,6.1,15.9,0.381
2,1610612739,Cleveland,Cavaliers,CLE,,82,48.7,104.3,16.9,0.481,...,0.473,18.2,40.7,0.447,1.7,5.7,0.299,9.0,23.9,0.378
3,1610612746,Los Angeles,Clippers,LAC,,82,48.6,104.5,15.0,0.497,...,0.480,18.9,42.0,0.450,2.0,6.0,0.334,7.7,20.8,0.373
4,1610612760,Oklahoma City,Thunder,OKC,,82,48.6,110.2,16.1,0.480,...,0.497,17.5,38.7,0.451,1.6,5.1,0.321,6.6,18.6,0.356
5,1610612737,Atlanta,Hawks,ATL,,82,48.6,102.8,19.0,0.463,...,0.483,19.4,44.6,0.435,1.0,3.1,0.311,9.0,25.3,0.355
6,1610612745,Houston,Rockets,HOU,,82,48.6,106.5,17.2,0.433,...,0.472,15.5,36.4,0.426,2.3,7.4,0.318,8.4,23.5,0.355
7,1610612757,Portland,Trail Blazers,POR,,82,48.5,105.1,17.5,0.441,...,0.447,18.0,39.8,0.453,1.7,5.9,0.295,8.8,22.6,0.389
8,1610612758,Sacramento,Kings,SAC,,81,48.4,106.7,18.7,0.452,...,0.473,18.1,39.7,0.454,0.9,3.1,0.276,7.2,19.4,0.372
9,1610612764,Washington,Wizards,WAS,,82,48.5,104.1,15.4,0.480,...,0.483,19.5,44.3,0.439,0.7,2.7,0.254,8.0,21.5,0.371
10,1610612748,Miami,Heat,MIA,,82,48.6,100.0,17.9,0.488,...,0.490,15.7,35.2,0.445,0.8,2.9,0.282,5.3,15.1,0.347
11,1610612761,Toronto,Raptors,TOR,,81,48.5,102.7,23.0,0.462,...,0.461,14.1,32.4,0.436,1.8,5.6,0.327,6.8,17.7,0.384
12,1610612742,Dallas,Mavericks,DAL,,82,49.0,102.3,18.2,0.473,...,0.464,17.5,41.4,0.423,1.4,5.3,0.273,8.4,23.3,0.360
13,1610612766,Charlotte,Hornets,CHA,,82,48.6,103.4,16.8,0.459,...,0.449,17.0,39.8,0.427,1.8,6.0,0.297,8.9,23.4,0.379
14,1610612762,Utah,Jazz,UTA,,82,49.0,97.7,18.1,0.445,...,0.468,15.9,37.2,0.426,1.4,4.3,0.318,7.1,19.5,0.363
15,1610612753,Orlando,Magic,ORL,,81,48.7,102.0,18.0,0.456,...,0.475,18.5,42.6,0.435,0.7,2.7,0.249,7.1,19.5,0.363
16,1610612749,Milwaukee,Bucks,MIL,,82,48.7,99.0,17.4,0.463,...,0.477,13.2,29.4,0.448,1.1,4.0,0.270,4.3,11.6,0.370
17,1610612740,New Orleans,Pelicans,NOP,,82,48.5,102.7,19.9,0.458,...,0.460,17.9,41.1,0.434,0.6,2.6,0.247,7.9,21.2,0.374
18,1610612750,Minnesota,Timberwolves,MIN,,82,48.6,102.4,15.1,0.464,...,0.471,16.1,35.4,0.455,0.7,2.6,0.272,4.8,13.8,0.350
19,1610612754,Indiana,Pacers,IND,,82,48.8,102.2,13.7,0.453,...,0.465,16.4,38.1,0.431,1.7,5.7,0.299,6.4,17.4,0.368
20,1610612751,Brooklyn,Nets,BKN,,82,48.4,98.6,14.4,0.457,...,0.464,15.8,36.1,0.438,1.0,3.3,0.303,5.5,15.1,0.363
21,1610612765,Detroit,Pistons,DET,,82,48.7,102.0,17.5,0.464,...,0.452,15.7,37.2,0.422,0.9,4.0,0.227,8.1,22.2,0.366
22,1610612743,Denver,Nuggets,DEN,,82,48.6,101.9,15.9,0.406,...,0.448,16.4,37.8,0.434,1.1,4.3,0.264,6.9,19.5,0.354
23,1610612738,Boston,Celtics,BOS,,81,48.5,105.6,18.9,0.453,...,0.451,16.9,39.9,0.424,1.6,5.7,0.274,7.1,20.3,0.350
24,1610612741,Chicago,Bulls,CHI,,82,48.9,101.6,18.1,0.458,...,0.442,17.0,38.5,0.441,1.3,3.9,0.332,6.6,17.5,0.380
25,1610612755,Philadelphia,76ers,PHI,,82,48.6,97.4,19.7,0.445,...,0.449,15.3,37.4,0.409,1.6,5.7,0.281,7.7,21.8,0.354
26,1610612756,Phoenix,Suns,PHX,,82,48.4,100.9,15.6,0.440,...,0.447,16.6,39.5,0.421,1.4,5.0,0.288,7.6,20.8,0.363
27,1610612752,New York,Knicks,NYK,,82,48.5,98.4,10.4,0.447,...,0.439,15.9,36.4,0.438,1.5,4.9,0.305,5.9,16.6,0.358
28,1610612763,Memphis,Grizzlies,MEM,,82,48.6,99.1,16.4,0.440,...,0.459,16.1,38.5,0.418,0.7,2.5,0.278,5.4,16.0,0.340
29,1610612747,Los Angeles,Lakers,LAL,,82,48.3,97.3,15.6,0.441,...,0.420,14.0,34.5,0.406,2.2,7.9,0.278,5.6,16.7,0.335

### Part e
Save the NBA dataframe you extracted in problem 4 as a JSON-formatted text file on your local machine. Format the JSON so that it is organized as dictionary with three lists: `columns` lists the column names, `index` lists the row names, and `data` is a list-of-lists of data points, one list for each row. [Hint: this is possible with one line of code] [8 points]

In [7]:
with open('nba_data.json', 'w') as f:
    f.write(shooting_df.to_json(orient='split' ))

## Problem 4
NASA has a pubic dataset of all asteroids that are in close proximity to Earth, searchable for any day, including today. The data contain the name of each asteroid, along with the absolute magnitude (a measure of luminosity), the minimum and maximum diameter in different units of measurement, the date and time of closest approach, the distance from Earth, and velocity of the astroid at the moment of its closest approach.

To access the data for today, change the first line in the following code block to today's date in YYYY-MM-DD format:

In [8]:
date = '2025-09-13'
url = f'https://api.nasa.gov/neo/rest/v1/feed?start_date={date}&end_date={date}&api_key=DEMO_KEY'
url

'https://api.nasa.gov/neo/rest/v1/feed?start_date=2025-09-13&end_date=2025-09-13&api_key=DEMO_KEY'

(Note: APIs are systems for exchanging data between servers and users on the internet. We will be discussing APIs in depth in module 4. The URL above specifies `api_key=DEMO_KEY`, which is for initially exploring APIs prior to signing up. The demo key has more restrictive limits on the amount of data a user can acquire than you can get by signing up for your own key. For module 4 we will work through the process of getting our own API keys and keeping them secret while writing Python code, but for this exercise using the demo key will work for what we need.)

Use your web-browser or https://jsonhero.io to view the JSON data from this URL and determine the correct path that leads to the records we want to populate the rows of a dataframe.

Then use `requests.get()`, `json.loads()`, and `pd.json_normalize()` to bring the data into Python and organize it in a dataframe. Use the `headers=myheaders` argument inside `requests.get()` to inform the NASA API about your user-agent string. [12 points]

In [9]:
res = requests.get(url, headers=myheaders)
json_data = json.loads(res.text)
neo_data = pd.json_normalize(json_data, record_path=["near_earth_objects", date], )
neo_data

,id,neo_reference_id,name,nasa_jpl_url,absolute_magnitude_h,is_potentially_hazardous_asteroid,close_approach_data,is_sentry_object,links.self,estimated_diameter.kilometers.estimated_diameter_min,estimated_diameter.kilometers.estimated_diameter_max,estimated_diameter.meters.estimated_diameter_min,estimated_diameter.meters.estimated_diameter_max,estimated_diameter.miles.estimated_diameter_min,estimated_diameter.miles.estimated_diameter_max,estimated_diameter.feet.estimated_diameter_min,estimated_diameter.feet.estimated_diameter_max,sentry_data
0,3313157,3313157,(2006 BA),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,27.600,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/3313157?ap...,0.008027,0.017949,8.027032,17.948988,0.004988,0.011153,26.335407,58.887759,NaN
1,3607530,3607530,(2012 PB20),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,24.790,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/3607530?ap...,0.029279,0.065470,29.278915,65.469644,0.018193,0.040681,96.059435,214.795427,NaN
2,3727640,3727640,(2015 SA),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,25.300,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/3727640?ap...,0.023150,0.051765,23.150212,51.765448,0.014385,0.032166,75.952142,169.834153,NaN
3,3759318,3759318,(2016 RT20),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,24.400,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/3759318?ap...,0.035039,0.078350,35.039264,78.350176,0.021772,0.048685,114.958219,257.054393,NaN
4,3819564,3819564,(2018 HW1),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,25.800,False,"[{'close_approach_date': '2025-09-13', 'close_...",True,http://api.nasa.gov/neo/rest/v1/neo/3819564?ap...,0.018389,0.041119,18.388867,41.118757,0.011426,0.025550,60.330931,134.904063,http://api.nasa.gov/neo/rest/v1/neo/sentry/381...
5,54055107,54055107,(2020 TA3),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,26.400,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/54055107?a...,0.013949,0.031192,13.949382,31.191767,0.008668,0.019382,45.765691,102.335197,NaN
6,54245589,54245589,(2022 CY2),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,25.550,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/54245589?a...,0.020633,0.046136,20.632648,46.136004,0.012821,0.028668,67.692418,151.364848,NaN
7,54282890,54282890,(2022 LA3),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,26.000,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/54282890?a...,0.016771,0.037501,16.770846,37.500752,0.010421,0.023302,55.022463,123.033968,NaN
8,54305030,54305030,(2022 SS2),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,27.160,False,"[{'close_approach_date': '2025-09-13', 'close_...",True,http://api.nasa.gov/neo/rest/v1/neo/54305030?a...,0.009830,0.021981,9.830033,21.980622,0.006108,0.013658,32.250766,72.114904,http://api.nasa.gov/neo/rest/v1/neo/sentry/543...
9,54377566,54377566,(2023 QU1),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,26.160,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/54377566?a...,0.015580,0.034837,15.579552,34.836938,0.009681,0.021647,51.114019,114.294421,NaN
10,54381673,54381673,(2023 RZ4),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,21.790,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/54381673?a...,0.116561,0.260639,116.561459,260.639347,0.072428,0.161954,382.419499,855.115995,NaN
11,54383282,54383282,(2023 RA10),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,28.800,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/54383282?a...,0.004619,0.010329,4.619075,10.328565,0.002870,0.006418,15.154445,33.886369,NaN
12,54542546,54542546,(2025 QA10),https://ssd.jpl.nasa.gov/tools/sbdb_lookup.htm...,25.209,False,"[{'close_approach_date': '2025-09-13', 'close_...",False,http://api.nasa.gov/neo/rest/v1/neo/54542546?a...,0.024141,0.053981,24.140984,53.980882,0.015001,0.033542,79.202707,177.102638,NaN

## Problem 5
Pull data in JSON format from Reddit's top 25 posts on [/r/popular](https://www.reddit.com/r/popular/top/). Start by using `requests.get()` with the `headers=myheaders` argument on the website: http://www.reddit.com/r/popular/top.json. Then use `json.loads()` to parse the JSON format as python dictionaries and lists. If you look at the result, you should see JSON data. (If instead you see an access denied message, wait a couple minutes, restart your notebook and try again.)

If you were to use `pd.json_normalize()` at this point, you would pull all of the features in the data into one dataframe, resulting in a dataframe with 172 columns. 

If we only wanted a few features, then looping across elements of the JSON list itself and extracting only the data we want may be a more efficient approach.

Use looping - and not `pd.read_json()` or `pd.json_normalize()` - to create a dataframe with 25 rows (one for each of the top 25 posts), and only columns for `subreddit`, `title`, `ups`, and `created_utc`. You can follow the example listed in [section 3.3.3 of Surfing the Data Pipeline with Python](https://jkropko.github.io/surfing-the-data-pipeline/ch3.html#looping-across-records-to-extract-datapoints) as a way to start. (Your result might be a dataframe without any column headers. You can set the `.columns` attribute of the dataframe to the list `['subreddit', 'title', 'ups', 'created_utc']`.) [12 points]

In [14]:
res = requests.get("https://www.reddit.com/r/popular/top.json", headers=(myheaders))
top25_json = json.loads(res.text)
if res.status_code==200:
    #this API appears to have a low request limit, so put this here to prevent error and just show me response if too many requests
    top25_json = top25_json['data']['children']
    top25 = pd.DataFrame([[d['data']['subreddit'], d['data']['title'], d['data']['ups'], d['data']['created_utc']] for d in top25_json])
    top25.columns = ['subreddit', 'title', 'ups', 'created_utc']
    top25
else:
    top25 = top25_json
top25

,subreddit,title,ups,created_utc
0,BeAmazed,The cat chose him even before he could choose ...,100602,1.757765e+09
1,oddlysatisfying,This cat curls up to a full circle.,95429,1.757772e+09
2,Damnthatsinteresting,Whole house is being moved with people still i...,71121,1.757779e+09
3,Whatcouldgowrong,WCGW dumping your drink on a car wash worker,66445,1.757786e+09
4,MurderedByWords,Exactly this,66051,1.757790e+09
5,BlueskySkeets,Only certain debates are valued until you are ...,64850,1.757782e+09
6,MadeMeSmile,"If you can be anything, be kind.",61485,1.757773e+09
7,BlueskySkeets,Mainstream media has failed us,60180,1.757799e+09
8,mildlyinteresting,My work started selling “MAGA Water”,55241,1.757794e+09
9,SipsTea,Work of art 🎨🖌️,54659,1.757810e+09
10,mildlyinfuriating,"My dad’s cable bill, he’s paying for channels ...",54066,1.757798e+09
11,Fauxmoi,Eileen Davidson (RHOBH) posts on IG about Char...,52817,1.757794e+09
12,interestingasfuck,Kid mentally adds 100 four-digit numbers in ju...,53499,1.757806e+09
13,MadeMeSmile,Owner decided to test their cat’s intelligence.,51809,1.757820e+09
14,BlackPeopleTwitter,incredible how many people are suddenly changi...,49038,1.757784e+09
15,nextfuckinglevel,Incredible skill of this street artist,47209,1.757811e+09
16,BlueskySkeets,That escalated quickly,47074,1.757815e+09
17,BlackPeopleTwitter,Funny how that works…,44144,1.757796e+09
18,Music,Coldplay fans ‘disappointed’ after Chris Marti...,42003,1.757763e+09
19,SipsTea,Back stage pass,41110,1.757783e+09
20,cats,Vroom vroooom,40969,1.757787e+09
21,simpsonsshitposting,They were so looking forward to it too!,40461,1.757774e+09
22,meirl,Meirl,39478,1.757763e+09
23,nottheonion,‘Just kill ‘em’: Fox host’s ‘sick’ suggestion ...,39602,1.757813e+09
24,politics,Brazil Stopped Its Trump. It’s Pathetic that W...,38123,1.757793e+09