# Lab Assignment 5: Web Scraping
## DS 6001

name: Cecelia Auerswald

### Instructions
Please answer the following questions as completely as possible using text, code, and the results of code as needed. Format your answers in a Jupyter notebook. To receive full credit, make sure you address every part of the problem, and make sure your document is formatted in a clean and professional way.

## Problem 0
Import the following packages:

In [100]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup


## Problem 1
Large language models are very impressive. They use deep neural networks with billions of parameters. They fine-tune results with clever approaches to reinforcement learning through human feedback. Many of them employ APIs with user interfaces that allow users to chat in natural language through a simple textbox, and receive a response in only a few seconds. And the societal impact of these models is undeniably enormous, to an extent we are only beginning to understand.

But, none of that is the most impressive part of LLMs. Like anything else in machine learning, the most impressive and difficult element of the work is the data collection.

The data used to train major LLMs is something that big companies communicate very little about. [OpenAI](https://help.openai.com/en/articles/7842364-how-chatgpt-and-our-foundation-models-are-developed) only says that GPT and other baseline models are trained on data that is "freely and openly accessible on the internet." Many commentators, such as Dr. Vered Shwartz, assistant professor in the University of British Columbia department of computer science, say that LLMs like GPT are trained on "[essentially the entire internet](https://science.ubc.ca/news/chatgpt-has-read-almost-whole-internet-hasnt-solved-its-diversity-issues)." Think about pulling the entire internet into a single model and tell me this isn't the most impressive thing about ChatGPT.

A primary training set for Open AI's GPT and other major LLMs is the corpus compiled by [Common Crawl](https://commoncrawl.org/faq), a nonprofit organization that describes itself as "dedicated to providing a copy of the Internet to Internet researchers, companies and individuals at no cost for the purpose of research and analysis." According to the [Mozilla Foundation](https://www.mozillafoundation.org/en/blog/Mozilla-Report-How-Common-Crawl-Data-Infrastructure-Shaped-the-Battle-Royale-over-Generative-AI/), "[o]ver 80% of GPT-3 tokens (a representation unit of text data) stemmed from Common Crawl. Many models published by other developers likewise rely heavily on it: the study analyzed 47 LLMs published between 2019 and October 2023 that power text generators and found at least 64% of them were trained on Common Crawl."

Common Crawl is a massive web scraping endeavor. But it's not necessarily a sophisticated one. Mostly, Common Crawl is downloading the raw HTML from the webpages it scrapes and extracting text from the HTML. A task like this is exactly the kind of thing we can use `requests` and `BeautifulSoup` to do. 

Common Crawl is also at the center of many controversies and legal actions regarding generative AI, such as the New York Times' copyright infringement [lawsuit](https://www.npr.org/2025/03/26/nx-s1-5288157/new-york-times-openai-copyright-case-goes-forward) against OpenAI, and concerns about bias and racism in LLMs stemming from their training data.

For this problem, please examine the [Common Crawl website](https://commoncrawl.org/) and read "[Training Data for the Price of a Sandwich: Common Crawl’s Impact on Generative AI](https://assets.mofoprod.net/network/documents/Common_Crawl_Mozilla_Foundation_2024.pdf)" by Stefan Baack for the Mozilla Foundation.

### Part a
If you want access to the latest Common Crawl dataset, where can you get it? How many website does the dataset contain? And outside of computational and storage costs, how much will it cost to obtain the data? (Use [Common Crawl's website](https://commoncrawl.org/) to answer this question) [8 points]

<strong>To access the latest Common Crawl dataset, you can go to the [Data Overview](https://commoncrawl.org/overview) page and choose the top dataset in the dropdown, currently `CC-MAIN-2025-38`. Once you've selected that dataset, you can see it was created this month, September 2025 and contains 2.39 billion pages. It is available to download for free.</strong>

### Part b
Is Common Crawl more useful for the pre-training or fine-tuning stage of the development of an LLM? Why is the Common Crawl corpus used by so many AI efforts, and why must it usually be altered or filtered in some way? (see pages 11-13 of Baack's article) [8 points]

<strong> Common Crawl data is most useful in the pre-training stage, when LLMs are inundated with very large amounts of uncurated data from which they learn basic text completion. This stage benefits from the use of very large, very diverse datasets to create the most comprehensive foundation. That kind of dataset can be difficult to source, but Common Crawl is free, readily available, and frequently updated, so its very popular for this use!</strong>

<strong>The problem with using un-filtered or un-altered Common Crawl data is that it is not all high quality data. Much of it is data that is "undesireable" to train an LLM, like hate speech and pornography, and there is a lot of essentially meaninginless and repetitive text like menus, errors, etc. People have created ready-to-use filtered versions of Common Crawl data because filtered Common Crawl data has become so popular and useful.</strong>

### Part c
Given how Common Crawl decides which URLs to crawl, what are three reasons why the data cannot be said to be the complete internet or a representative sample of it? (see pages 17-22 of Baack's article) [8 points]

<strong>Much of the current internet is in video (Youtube, TikTok, etc.) and images (memes!), but none of that content is captured by Common Crawl, which only captures HTML content as text.</strong>

<strong>Additionally, Common Crawl's process gives the biggest weight and attention to pages that are frequently linked to on the web. This means that the data is skewed in favor of the largest, most-connected communities. This process excludes or under-weighs "digitally marginalized" and smaller communities that are less likely to have a connected presence within the web. This also means that English-language sites are over-represeneted in the data, along with English-speaking regions. While Common Crawl collects a huge amount of data, much of the internet is still ignored, and the resulting sample collected by Common Crawl is biased.</strong>

<strong>Lastly, some sites do not want their data scraped for use in AI models. As a result, a few large sites have blocked Common Crawl from accessing some or all of their pages, meaning that some of the most impactful, most highly viewed pages on the web are not included.</strong

### Part d
Of the suggestions that the Mozilla Foundation make for the future development of Common Crawl, are there any that you especially agree with or disagree with, and why? (See pages 30-31 of Baack's article) [8 points]

<strong>I agree with many of the suggestions but one that seemed both very wise and implementable was the suggestion that Common Crawl increase its transparency. With the popularity of Open Source projects, there is a strong precedent for transparency in the tech community. Especially because the ethos of the company appears to be open access and innovation, it follows that they would advocate for transparency and education. Engaging with the community and helping users understand how to most effectively use their project can only help them and the field of Artificial Intelligence in the long term. Additionally, if "neutrality" is one of their stated values, being candid about their finances is a must. 
</strong>


## Problem 2
For the following problems, you will be scraping http://books.toscrape.com/. This website is a fake book retailer, designed to mimic the design of many retail websites. It exists solely to help students practice web-scraping, so there aren’t going to be any ethical concerns with this particular exercise, and there shouldn’t be any issues with rate limits or other gates that could prevent web-scraping. Take a moment and look at this website, so that you know what you will be working with.

Your goal is to generate a dataframe with four columns: one for the title, one for the price, one for the star-rating, and one or the book cover JPEG’s URL. The dataframe will also 1000 rows, one for each of the 1000 books listed on the 50 pages of this website.

### Part a
Pull the HTML code from http://books.toscrape.com/. Make sure you provide the correct user agent string. Then parse this HTML code and save the parsed code as a separate Python variable. [8 points]

In [101]:
headers = {'user-agent': 
    'Data Arch Pipeline class Lab 5 (ccv4xb@virginia.edu) (Language=Python 3.13.2; Platform=Mac OSX 15.6.1)'}
r = requests.get("https://books.toscrape.com", headers = headers)
bts = BeautifulSoup(r.text, 'html.parser')

### Part b
Extract all 20 of the book titles and save them in a list. [8 points]

In [102]:
titles =[b.attrs['title'] for b in bts.find_all('a', title=True)]
titles

['A Light in the Attic',
 'Tipping the Velvet',
 'Soumission',
 'Sharp Objects',
 'Sapiens: A Brief History of Humankind',
 'The Requiem Red',
 'The Dirty Little Secrets of Getting Your Dream Job',
 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
 'The Black Maria',
 'Starving Hearts (Triangular Trade Trilogy, #1)',
 "Shakespeare's Sonnets",
 'Set Me Free',
 "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
 'Rip it Up and Start Again',
 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
 'Olio',
 'Mesaerion: The Best Science Fiction Stories 1800-1849',
 'Libertarianism for Beginners',
 "It's Only the Himalayas"]

### Part c
Extract the price of each of the 20 books and save these prices in a list. (The prices are listed in British pounds, and include the £ symbol. Remove the £ symbols: if you’ve saved the prices in a list named `prices`, then the following code should work: `prices = [s.replace('Â£', '') for s in prices]`.) [8 points]

In [103]:
prices = [float(p.string.replace('Â£', '')) for p in bts.find_all("p", "price_color")]
# first_prices = [p.string.replace('Â', '') for p in bts.find_all("p", "price_color")] 
#for the string version

print(prices)

[51.77, 53.74, 50.1, 47.82, 54.23, 22.65, 33.34, 17.93, 22.6, 52.15, 13.99, 20.66, 17.46, 52.29, 35.02, 57.25, 23.88, 37.59, 51.33, 45.17]

### Part d
Extract the star level ratings for the 20 books. [Hint: for tags such as `<p class="star-rating One">` in which the class has a space, the class is actually a list in which the first item in the list is `"star-rating"` and the second item in the list is `"One"`. It's possible to search on either item in this list.][8 points]

In [104]:
ratings = [p['class'][1] for p in bts.find_all('p', "star-rating")]
print(ratings)

['Three', 'One', 'One', 'Four', 'Five', 'One', 'Four', 'Three', 'Four', 'One', 'Two', 'Four', 'Five', 'Five', 'Five', 'Three', 'One', 'One', 'Two', 'Two']

### Part e
Extract the URLs for the JPEG thumbnail images that show the covers of the 20 books. (Maybe we want to mine the images to build models that predict the star level, literally judging books by their covers.) [8 points]

In [105]:
image_urls = [url.attrs['src'] for url in bts.find_all('img', 'thumbnail')]
image_urls

['media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg',
 'media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg',
 'media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg',
 'media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg',
 'media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg',
 'media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg',
 'media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg',
 'media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg',
 'media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg',
 'media/cache/58/46/5846057e28022268153beff6d352b06c.jpg',
 'media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg',
 'media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg',
 'media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg',
 'media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg',
 'media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg',
 'media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg',
 'media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg',
 'media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg',
 'media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg',
 'media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg']

### Part f
Create a dataframe with one row for each of the 20 books, and the book titles, prices, star ratings, and cover JPEG URLs as the four columns. [8 points]

In [106]:
book_data = {'title': titles, 'price': prices, 'rating': ratings, 'image_url': image_urls}
books_df = pd.DataFrame(book_data)
books_df

,title,price,rating,image_url
0,A Light in the Attic,51.77,Three,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...
1,Tipping the Velvet,53.74,One,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...
2,Soumission,50.10,One,media/cache/3e/ef/3eef99c9d9adef34639f51066202...
3,Sharp Objects,47.82,Four,media/cache/32/51/3251cf3a3412f53f339e42cac213...
4,Sapiens: A Brief History of Humankind,54.23,Five,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...
5,The Requiem Red,22.65,One,media/cache/68/33/68339b4c9bc034267e1da611ab3b...
6,The Dirty Little Secrets of Getting Your Dream...,33.34,Four,media/cache/92/27/92274a95b7c251fea59a2b8a7827...
7,The Coming Woman: A Novel Based on the Life of...,17.93,Three,media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78...
8,The Boys in the Boat: Nine Americans and Their...,22.60,Four,media/cache/66/88/66883b91f6804b2323c8369331cb...
9,The Black Maria,52.15,One,media/cache/58/46/5846057e28022268153beff6d352...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",13.99,Two,media/cache/be/f4/bef44da28c98f905a3ebec0b87be...
11,Shakespeare's Sonnets,20.66,Four,media/cache/10/48/1048f63d3b5061cd2f424d20b3f9...
12,Set Me Free,17.46,Five,media/cache/5b/88/5b88c52633f53cacf162c15f4f82...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,Five,media/cache/94/b1/94b1b8b244bce9677c2f29ccc890...
14,Rip it Up and Start Again,35.02,Five,media/cache/81/c4/81c4a973364e17d01f217e118825...
15,Our Band Could Be Your Life: Scenes from the A...,57.25,Three,media/cache/54/60/54607fe8945897cdcced0044103b...
16,Olio,23.88,One,media/cache/55/33/553310a7162dfbc2c6d19a84da0d...
17,Mesaerion: The Best Science Fiction Stories 18...,37.59,One,media/cache/09/a3/09a3aef48557576e1a85ba7efea8...
18,Libertarianism for Beginners,51.33,Two,media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736...
19,It's Only the Himalayas,45.17,Two,media/cache/27/a5/27a53d0bb95bdd88288eaf66c923...

### Part g
Create a function that takes the URL of the webpage to scrape as an input, applies the code you wrote for parts a through e, and generates the dataframe from part f as the output. [10 points]

In [107]:
def scrape_page_for_books(url):
    headers = {'user-agent': 
        'Data Arch Pipeline class Lab 5 (ccv4xb@virginia.edu) (Language=Python 3.13.2; Platform=Mac OSX 15.6.1)'}
    r = requests.get(url, headers = headers)
    bts = BeautifulSoup(r.text, 'html.parser')
    titles =[b.attrs['title'] for b in bts.find_all('a', title=True)]
    prices = [float(p.string.replace('Â£', '')) for p in bts.find_all("p", "price_color")]
    ratings = [p['class'][1] for p in bts.find_all('p', "star-rating")]
    image_urls = [url.attrs['src'] for url in bts.find_all('img', 'thumbnail')]
    book_data = {'title': titles, 
                 'price': prices, 
                 'rating': ratings, 
                 'image_url': image_urls
                }
    books_df = pd.DataFrame(book_data)
    return books_df

### Part h
Notice that there are many pages to http://books.toscrape.com/. When you click on “Next” in the bottom-right corner of the screen, it takes you to http://books.toscrape.com/catalogue/page-2.html. The front page is the same as http://books.toscrape.com/catalogue/page-1.html, and there are 50 total pages.

Write a loop that uses the function you wrote in part g to scrape each of the 50 pages, and append each of these data frames together. If you write this loop correctly, your dataframe will have 1000 rows (20 books on each of the 50 pages). 

Some hints:

* Typing `new_df = pd.DataFrame()` with nothing in the parentheses will create an empty data frame on which new data can be appended.

* There are many loops you can use, but the most straightforward one is a for-values loop that counts from 1 to 50. In Python, you can initialize such a loop with for i in range(1, 51):, and indenting every line below it that belongs inside the loop. Inside the loop, the letter i is now a stand-in for the number currently being considered.

* You will need to figure out how to replace the number in URLs like http://books.toscrape.com/catalogue/page-2.html with the number currently under consideration in the loop. You might need the `str()` function, which turns numeric values into strings.

* `pd.concat()` is a method that appends dataframes together.

[10 points]

In [110]:
book_data = pd.DataFrame()
base_url = "https://books.toscrape.com/"
next_url = base_url
for i in range(0,50):
    next_data = scrape_page_for_books(next_url)
    book_data = pd.concat([book_data, next_data], ignore_index=True)
    next_url = base_url + "catalogue/page-" + str(i+2) + ".html"

In [111]:
book_data

,title,price,rating,image_url
0,A Light in the Attic,51.77,Three,media/cache/2c/da/2cdad67c44b002e7ead0cc35693c...
1,Tipping the Velvet,53.74,One,media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f...
2,Soumission,50.10,One,media/cache/3e/ef/3eef99c9d9adef34639f51066202...
3,Sharp Objects,47.82,Four,media/cache/32/51/3251cf3a3412f53f339e42cac213...
4,Sapiens: A Brief History of Humankind,54.23,Five,media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c...
...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,One,../media/cache/96/ee/96ee77d71a31b7694dac6855f...
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,Four,../media/cache/09/7c/097cb5ecc6fb3fbe1690cf0cb...
997,A Spy's Devotion (The Regency Spies of London #1),16.97,Five,../media/cache/1b/5f/1b5ff86f3c75e51e24c573d3f...
998,1st to Die (Women's Murder Club #1),53.98,One,../media/cache/2b/41/2b4161c5b72a4ae386b644682...
999,"1,000 Places to See Before You Die",26.08,Five,../media/cache/d7/0f/d70f7edd92705c45a82118c3f...