# Lab Assignment 2: How to Load CSV, ASCII, and other data into Python
## DS 6001

100 points

### Instructions
Please answer the following questions as completely as possible using text, code, and the results of code as needed. Format your answers in a Jupyter notebook. To receive full credit, make sure you address every part of the problem, and make sure your document is formatted in a clean and professional way.

## Problem 1

There are several data files attached to this lab assignment, with different extensions. First, download all of these data files, and save them in the same folder on your local machine. Your task in the following questions is to load each file into Python correctly, so that you can begin the process of data cleaning. If the variable names are included in the file, use those names to name the columns. If the variable names are not included, use these names in order:

In [1]:
column_names = ["Country", "Happiness score", "Whisker-high", "Whisker-low", 
  "Dystopia (1.92) + residual", "Explained by: GDP per capita", 
  "Explained by: Social support", "Explained by: Healthy life expectancy", 
  "Explained by: Freedom to make life choices", "Explained by: Generosity", 
  "Explained by: Perceptions of corruption" ]

### Part a
Import the packages you will need. Then write code to change the working directory to the folder in which you saved the data files, run the code displayed above to create the `column_names` list, load `data_clean.csv`, and display the output of the `.info()` method of `data_clean`. [4 points]

In [2]:
import pandas as pd
import os 
os.chdir('/Users/ceceliaauerswald/UVA_MSDS/Data_Pipeline_Arch/Module 2/Homework/lab data')

data_clean = pd.read_csv('data_clean.csv')

data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     156 non-null    object
 1   Happiness score                             156 non-null    float64
 2   Whisker-high                                156 non-null    float64
 3   Whisker-low                                 156 non-null    float64
 4   Dystopia (1.92) + residual                  156 non-null    float64
 5   Explained by: GDP per capita                156 non-null    float64
 6   Explained by: Social support                156 non-null    float64
 7   Explained by: Healthy life expectancy       156 non-null    float64
 8   Explained by: Freedom to make life choices  156 non-null    float64
 9   Explained by: Generosity                    156 non-null    float64
 10  Explained by: Perceptions of corruption     156 non-null    float64
dtypes: float64(10), object(1)
memory usage: 13.5+ KB

### Part b
Load `data1.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

<strong>By using the head() and info() methods on the data1 dataframe, I saw that there were 2 rows of metadata. I could either use header=2 or skiprows=2 to fix this, and I chose header.</strong>

In [3]:
data1 = pd.read_csv('data1.csv')
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 11 columns):
 #   Column                                                                                           Non-Null Count  Dtype
---  ------                                                                                           --------------  -----
 0   Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)  158 non-null    object
 1   Unnamed: 1                                                                                       157 non-null    object
 2   Unnamed: 2                                                                                       157 non-null    object
 3   Unnamed: 3                                                                                       157 non-null    object
 4   Unnamed: 4                                                                                       157 non-null    object
 5   Unnamed: 5                                                                                       157 non-null    object
 6   Unnamed: 6                                                                                       157 non-null    object
 7   Unnamed: 7                                                                                       157 non-null    object
 8   Unnamed: 8                                                                                       157 non-null    object
 9   Unnamed: 9                                                                                       157 non-null    object
 10  Unnamed: 10                                                                                      157 non-null    object
dtypes: object(11)
memory usage: 13.7+ KB

In [4]:
data1.head()

,"Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,URL: http://worldhappiness.report/ed/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
2,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
3,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
4,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408

In [5]:
data1 = pd.read_csv('data1.csv', header=2)
data1.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

### Part c
Load `data2.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [6 points]

<strong>After loading in the data and checking the first 5 rows with head(), I saw that there were 2 rows of metadata. Once I removed the metadata at the top with header=2, I noticed that this version of the data contained some exta comments in rhe data about how it was organized. Because those comments started with "/" and none of the countries or numerical data also start that way, I used the comment parameter to remove those comments from the data.</strong>

In [6]:
data2 = pd.read_csv('data2.txt')
data2.head()

,"Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,URL: http://worldhappiness.report/ed/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
2,"/The following countries comprise the ""very ha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
4,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340

In [7]:
data2 = pd.read_csv('data2.txt', header=2)
data2.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,"/The following countries comprise the ""very ha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
2,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
3,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
4,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138

In [8]:
data2 = pd.read_csv('data2.txt', header=2, comment='/')
data2.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

### Part d
Load `data3.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

<strong> By looking at the first 5 rows of data (using head()), I saw that the automatic choice of a comma as the delimiter was incorrect. Addtionally, I saw that there were 2 rows of metadata. I used header=2 to remove the metedata and specified "\t" (tab) as the delimiter using sep="\t". </strong>

In [9]:
data3 = pd.read_csv('data3.txt')
data3.head()

  Source: The World Happiness Report (2018), The Sustainable Development Solutions Network (SDSN)\t\t\t\t\t\t\t\t\t\t
0  URL: http://worldhappiness.report/ed/2018\t\t\...
1  Country\tHappiness score\tWhisker-high\tWhiske...
2  Finland\t7.632\t7.695\t7.569\t2.595\t1.305\t1....
3  Norway\t7.594\t7.657\t7.53\t2.383\t1.456\t1.58...
4  Denmark\t7.555\t7.623\t7.487\t2.37\t1.351\t1.5...

In [10]:
data3 = pd.read_csv('data3.txt', skiprows=2, sep='\t')
data3.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

### Part e
Load `data4.txt`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

<strong> When I loaded data 4, I saw that the delimiter was "$" and there were no column names in the file. I specified the delimiter with sep="$". Then, I set the columns with the names parameter of read_csv and ensured that the first line of data would not be lost with header=None.</strong>

In [11]:
data4 = pd.read_csv('data4.txt')
data4.head()

  Finland$7.632$7.695$7.569$2.595$1.305$1.592$0.874$0.681$0.192$0.393
0  Norway$7.594$7.657$7.530$2.383$1.456$1.582$0.8...
1  Denmark$7.555$7.623$7.487$2.370$1.351$1.590$0....
2  Iceland$7.495$7.593$7.398$2.426$1.343$1.644$0....
3  Switzerland$7.487$7.570$7.405$2.320$1.420$1.54...
4  Netherlands$7.441$7.498$7.384$2.448$1.361$1.48...

In [12]:
data4 = pd.read_csv('data4.txt', sep='$', header=None, names=column_names)
data4.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

### Part f
Load `data5.csv`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

<strong> When I looked at the head for this file, everything looked good. Then I checked the tail and I saw that the last couple rows of the file were extra info. Using the docstring for read_csv, I found that the skipfooter parameter would make the method ignore lines from the end of the file. I used skipfooter=2 to ignore the last 2 lines of metadata.</strong>

In [13]:
data5 = pd.read_csv('data5.csv')
data5.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [14]:
data5.tail()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076
156,"Source: The World Happiness Report (2018), The...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,URL: http://worldhappiness.report/ed/2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
data5 = pd.read_csv('data5.csv', skipfooter=2)
data5.tail()

/var/folders/fm/2_zxw4w57231pbsnw1dv90yc0000gn/T/ipykernel_67642/1887529852.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  data5 = pd.read_csv('data5.csv', skipfooter=2)

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,0.627,0.145,0.065,0.149,0.076

### Part g
Load `data6.dat`. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. (Note: for this question, your result won't look *exactly* like data_clean.csv, and that is OK.) [6 points]

<strong> When I loaded this data, I saw that some of the values were 999. Because that value does not make sense for the information represented by the data, it appears to represent the absensce of data. I used the na_values parameter to convert this to NaN, which pandas will recognize as no data.</strong>

In [16]:
data6 = pd.read_csv('data6.dat')
data6.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,999.000,999.000,999.000,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,999.000,999.000,1.582,999.000,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,999.000,0.683,0.284,0.408
3,Iceland,7.495,7.593,999.000,2.426,1.343,1.644,0.914,0.677,0.353,999.000
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [17]:
data6 = pd.read_csv('data6.dat', na_values = 999)
data6.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,NaN,NaN,NaN,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,NaN,NaN,1.582,NaN,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,NaN,0.683,0.284,0.408
3,Iceland,7.495,7.593,NaN,2.426,1.343,1.644,0.914,0.677,0.353,NaN
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

### Part h
Load `data7.xlsx`, which is an Excel file. Keep only the sheet named “Data”. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

<strong> I loaded the excel sheet using read_excel and specifying the sheet to grab with sheet_name. Then I checked the data using info(), head(), and tail(). I also compared to data_clean. All appeared to be ok!</strong>

In [18]:
data7 = pd.read_excel('data7.xlsx', sheet_name='Data')
data7.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

### Part i
Load `data8.dta`, which is a Stata 13 file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

<strong>I loaded this file using read_stata. Once it had loaded, I saw using head() and info() that the column names were messy and that the data was type float32, not float64 like the other data. While neither is a major problem for usability, it was easy to fix the columns. To do so, because read_stata has no argument that sets the column headers, I set them manually using the columns attribute of the dataframe after it was created. [Before I did this, I made sure that the columns matched the given list of column names.]</strong>

In [19]:
data8 = pd.read_stata('data8.dta')
data8.head()

,country,happinessscore,whiskerhigh,whiskerlow,dystopia192residual,explainedbygdppercapita,explainedbysocialsupport,explainedbyhealthylifeexpectancy,explainedbyfreedomtomakelifechoi,explainedbygenerosity,explainedbyperceptionsofcorrupti
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [20]:
data8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   country                           156 non-null    object
 1   happinessscore                    156 non-null    float32
 2   whiskerhigh                       156 non-null    float32
 3   whiskerlow                        156 non-null    float32
 4   dystopia192residual               156 non-null    float32
 5   explainedbygdppercapita           156 non-null    float32
 6   explainedbysocialsupport          156 non-null    float32
 7   explainedbyhealthylifeexpectancy  156 non-null    float32
 8   explainedbyfreedomtomakelifechoi  156 non-null    float32
 9   explainedbygenerosity             156 non-null    float32
 10  explainedbyperceptionsofcorrupti  156 non-null    float32
dtypes: float32(10), object(1)
memory usage: 7.4+ KB

In [21]:
data8.columns = column_names
data8.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

### Part j
Load `data9.sav`, which is an SPSS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. [4 points]

<strong> I loaded this data file using read_spss, and saw that the column names were somewhat messy. I confirmed that the columns were the same and the same order as the given column names, then used the given list to rename the columns. Otherwise, the data appeared ready to go.</strong>

In [22]:
data9 = pd.read_spss('data9.sav')
data9.head()

,country,happiness,whiskerhigh,whiskerlow,dystopia,gdpPC,socsupport,lifeexp,lifechoice,generous,corrupt
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [23]:
data9.columns = column_names
data9.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

### Part k
Load `data10.xpt`, which is a SAS file. Use the tools we discussed in class to decide whether the data file loaded correctly, and include that code in your lab report. In one or two sentences, describe how you decided on the right combination of parameters needed to load the data. 

(If some of the country names display as `b'Finland'`, don't worry about that.)

(But if you are still worrying about it ... issues like `b'Finland'` indicate a [character encoding](https://en.wikipedia.org/wiki/Character_encoding) issue, in which SAS uses a different encoding method than Python. In this case Python uses a default encoding called [UTF-8](https://en.wikipedia.org/wiki/UTF-8) and this SAS file has encoded characters using [Latin-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1). To get around this issue, add the `encoding='latin-1'` argument to your read method.) 

[4 points]

<strong> I loaded this file using read_sas. The column names were not very helpful to explain the data, so I replaced them with the clearer list of column names we have, because we know what the data represents. I also chose to fix the encoding, because why not? There did not appear to be any other issues with the data.</strong>

In [24]:
data10 = pd.read_sas('data10.xpt')
data10.head()

,COUNTRY,HAPPINES,WHISKERH,WHISKERL,DYSTOPIA,EXPLAINE,EXPLAIN2,EXPLAIN3,EXPLAIN4,EXPLAIN5,EXPLAIN6
0,b'Finland',7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,b'Norway',7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,b'Denmark',7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,b'Iceland',7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,b'Switzerland',7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [25]:
data10 = pd.read_sas('data10.xpt', encoding='latin-1')
data10.columns = column_names
data10.tail()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
151,Yemen,3.355,3.448,3.262,1.106,0.442,1.073000e+00,0.343,0.244,0.083,0.064
152,Tanzania,3.303,3.414,3.193,0.628,0.455,9.910000e-01,0.381,0.481,0.270,0.097
153,South Sudan,3.254,3.385,3.123,1.691,0.337,6.080000e-01,0.177,0.112,0.224,0.106
154,Central African Republic,3.083,3.227,2.939,2.487,0.024,5.397605e-79,0.010,0.305,0.218,0.038
155,Burundi,2.905,3.074,2.735,1.752,0.091,6.270000e-01,0.145,0.065,0.149,0.076

### Part l
Please load the `data11.txt` file, which is a fixed width file. The columns are defined as follows:

| Variable                                   | Width | Start | End |
|--------------------------------------------|-------|-------|-----|
| Country                                    | 24    | 1     | 24  |
| Happiness score                            | 5     | 25    | 29  |
| Whisker-high                               | 5     | 30    | 34  |
| Whisker-low                                | 5     | 35    | 39  |
| Dystopia (1.92) + residual                 | 5     | 40    | 44  |
| Explained by: GDP per capita               | 5     | 45    | 49  |
| Explained by: Social support               | 5     | 50    | 54  |
| Explained by: Healthy life expectancy      | 5     | 55    | 59  |
| Explained by: Freedom to make life choices | 5     | 60    | 64  |
| Explained by: Generosity                   | 5     | 65    | 69  |
| Explained by: Perceptions of corruption    | 5     | 70    | 74  |

Then save the this loaded data frame as a CSV file on your local machine. Be sure to use a unique filename so as not to overwrite any existing files. [10 points]

In [26]:
datawidths = [24,5,5,5,5,5,5,5,5,5,5]
#datapos = [(0,24),(24,29),(29,34),(34,39),(39,44),(44,49),(49,54),(54,59),(59,64),(64,69),(69,74)]

data11 = pd.read_fwf('data11.txt', widths=datawidths, names=column_names)
#data11_alt = pd.read_fwf('data11.txt', colspecs=datapos, names=column_names)

data11.head()

,Country,Happiness score,Whisker-high,Whisker-low,Dystopia (1.92) + residual,Explained by: GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption
0,Finland,7.632,7.695,7.569,2.595,1.305,1.592,0.874,0.681,0.192,0.393
1,Norway,7.594,7.657,7.530,2.383,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,7.555,7.623,7.487,2.370,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,7.495,7.593,7.398,2.426,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,7.487,7.570,7.405,2.320,1.420,1.549,0.927,0.660,0.256,0.357

In [27]:
data11.to_csv('cecelia_data11.csv', index=False)

## Problem 2
This problem walks through how to wrangle some difficult real-world Excel data into Python. This problem is guided, but later in the semester you'll be asked more often to do work with less guidance. 

The file named "epa_data.xlsx" contains data on the reproduction and growth of nine different plant species, measured once in 2010 and once in 2011. The data were compiled from the [EPA's repository](https://catalog.data.gov/dataset/18-excel-spreadsheets-by-species-and-year-giving-reproduction-and-growth-data-one-excel-sp) on data.gov. I placed all of the data into a single file, where the different species/year combinations are placed in different sheets. The file also includes a sheet for herbicide treatment chemistry data, and one sheet for a ReadMe describing some of the columns in the growth data.

### Part a
If you load an Excel file with multiple sheets into Python using the `sheet_name=None` argument, then every sheet's data will be stored in one big Python dictionary. 

We will discuss dictionaries (and JSON formatted data) in depth in module 3. However, for this problem, there a few points to know about dictionaries:

* Dictionaries are similar to lists, except that they are denoted with curly braces {} instead of square braces [], and that entries in the dictionary are indexed by names instead of numeric positions.

* Entries in a dictionary are called values, and the names attached to the entries are called keys. Your output will set the former sheet names as the keys for each data table.

* To display one of the values, call the Python variable that contains the dictionary, and index it by the value's key. For example, if you save the data as `epadata`, then you can see the 2010 data for species CALE by typing `epadata['CALE 2010']`. 

Load all of the data, across all of the sheets, from this Excel file into Python. Then index to one of the values in the resulting dictionary to display one of the former sheets as a pandas dataframe. [8 points]

In [28]:
epa_data = pd.read_excel('epa_data.xlsx', sheet_name=None)
epa_data.keys()

dict_keys(['CALE 2010', 'CALE 2011', 'ELGL 2010', 'ELGL 2011', 'ERLA 2010', 'ERLA 2011', 'FEID 2010', 'FEID 2011', 'FRVI 2010', 'FRVI 2011', 'IRTE 2010', 'IRTE 2011', 'POGR 2010', 'POGR 2011', 'PRVU 2010', 'PRVU 2011', 'RAOC 2010', 'RAOC 2011', 'Solution Chemistry', 'ReadMe'])

In [29]:
feid2011 = epa_data['FEID 2011']
feid2011

,species,year,site,Plot,trt,Treatment,cover0,arsincover0,cover5,arsincover5,...,immatureseedw,logimmatureseeddw,totalseeddw,logtotalseeddw,percentimmatureseed,arsinpercentimmatureseed,biomass,logbiomass,Previous Treatment Comments,Final Comments
0,FEID,2011,Hyslop,2,6,Roundup 0.2,2.0,0.141897,2.0,0.141897,...,0.0000,-5.000000,0.0000,-5.000000,NaN,NaN,3.5,0.545307,NaN,NaN
1,FEID,2011,Hyslop,6,1,Carrier Control,6.0,0.247467,8.0,0.286757,...,0.0000,-5.000000,0.0000,-5.000000,NaN,NaN,13.3,1.124178,NaN,NaN
2,FEID,2011,Hyslop,12,4,Banvel 0.2,10.0,0.321751,15.0,0.397699,...,0.6204,-0.207321,1.0380,0.016202,59.768786,0.883718,42.7,1.630530,Rdup+Bnvl 0.01,NaN
3,FEID,2011,Hyslop,13,2,No Spray,14.0,0.383497,10.0,0.321751,...,1.3835,0.140982,5.5331,0.742969,25.004066,0.523646,49.4,1.693815,Roundup 0.01,NaN
4,FEID,2011,Hyslop,17,2,No Spray,5.0,0.225513,5.0,0.225513,...,0.0619,-1.208239,0.1332,-0.875463,46.471471,0.750084,7.0,0.845718,Banvel 0.01,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,FEID,2011,Botany,370,8,Rdup+Bnvl 0.2,7.0,0.267763,15.0,0.397699,...,0.0000,-5.000000,0.0000,-5.000000,NaN,NaN,17.2,1.235781,NaN,NaN
124,FEID,2011,Botany,377,3,Banvel 0.1,6.0,0.247467,5.0,0.225513,...,0.1277,-0.893775,0.5531,-0.257188,23.088049,0.501225,8.9,0.949878,Banvel 0.1,NaN
125,FEID,2011,Botany,379,4,Banvel 0.2,6.0,0.247467,10.0,0.321751,...,0.1014,-0.993919,0.3536,-0.451475,28.676471,0.565105,26.5,1.423410,no spray,NaN
126,FEID,2011,Botany,380,2,No Spray,6.0,0.247467,9.0,0.304693,...,0.1506,-0.822146,0.6569,-0.182494,22.925864,0.499298,18.1,1.257918,Rdup/Bnvl 0.01,NaN
127,FEID,2011,Botany,382,4,Banvel 0.2,10.0,0.321751,7.0,0.267763,...,3.0903,0.490002,6.3289,0.801329,48.828390,0.773681,41.6,1.619198,Rdup/Bnvl 0.1,NaN

### Part b
To see all of the keys in the dictionary, use the `.keys()` method on the data dictionary you created in part a. If you do, you will notice that two keys are not like the others:

* `Solution Chemistry` contains different data: information about common pesticides instead of the growth and reproduction of a particular species of plant.

* `ReadMe` contains descriptions of some columns in the species-level data.

To delete a key and value from a dictionary, use the following syntax `del d[key]`, where `d` is the Python variable that contains the dictionary, and `key` is the name (quotes included) of the key attached to the value you want to remove from the dictionary. If you use this command, the dictionary is altered *in place*, meaning that there is no need to write `d=` before this command in order to make these edits to the dictionary permanent.

Delete the `Solution Chemistry` and `ReadMe` data from the dictionary. [8 points]

In [30]:
epa_data.keys()

dict_keys(['CALE 2010', 'CALE 2011', 'ELGL 2010', 'ELGL 2011', 'ERLA 2010', 'ERLA 2011', 'FEID 2010', 'FEID 2011', 'FRVI 2010', 'FRVI 2011', 'IRTE 2010', 'IRTE 2011', 'POGR 2010', 'POGR 2011', 'PRVU 2010', 'PRVU 2011', 'RAOC 2010', 'RAOC 2011', 'Solution Chemistry', 'ReadMe'])

In [31]:
del epa_data['Solution Chemistry']
del epa_data['ReadMe']
epa_data.keys()

dict_keys(['CALE 2010', 'CALE 2011', 'ELGL 2010', 'ELGL 2011', 'ERLA 2010', 'ERLA 2011', 'FEID 2010', 'FEID 2011', 'FRVI 2010', 'FRVI 2011', 'IRTE 2010', 'IRTE 2011', 'POGR 2010', 'POGR 2011', 'PRVU 2010', 'PRVU 2011', 'RAOC 2010', 'RAOC 2011'])

### Part c
Combining two data tables with the same columns but entirely different rows is called **appending** data. Our goal is to append all of the remaining data tables together, to create one large dataframe containing all plant species and both 2010 and 2011 data. 

It is only possible, however, to append data if both data tables have exactly the same column names. If a column in one table is not matched in the other table, the column will be populated with missing values for the rows that come from the second table. There are two reasons why columns might not match: the two tables might not contain the same features, or the two tables contain the same feature but named differently in each table. 

For example, in this case, some of the sheets have columns that others do not, such as biomass. Other features are present in every sheet, but with different names: year is sometimes spelled with a capital Y.

To deal with these issues, we will use a loop over the keys in the dictionary you edited in part b. Begin the loop by typing 
```
for df in d.keys():
```
where `d` is the name of your dictionary.

On the next line, indent (which indicates this line should be run within the loop). Then write
```
d[df].columns = d[df].columns.str.lower()
```
which will alter all column names across all of the dataframes to be lower-case.

In addition, some of the column names have extra spaces at the end, and that will make columns fail to match as well. To remove these spaces, add the following line to the loop:

```
d[df].columns = d[df].columns.str.strip()
```
which removes leading and trailing spaces from each column name. [10 points]

In [32]:
for df in epa_data.keys():
    epa_data[df].columns = epa_data[df].columns.str.lower()
    epa_data[df].columns = epa_data[df].columns.str.strip()

### Part d
Use the `pd.concat()` method to append all of the dataframes in your dictionary together. You can pass the entire dictionary to the first argument of `pd.concat()`. Specify `ignore_index=True`, which resets the row numbering instead of bringing in the old row numbers from the individual dataframes. [8 points]

In [33]:
combined_epa_data = pd.concat(epa_data, ignore_index=True)
combined_epa_data

,year,species,site,plot,trt,treatment,pods,sqrtpods,cover0,arsincover0,...,totseeddw,infloroescences,sqrtinfluorescences,atypicalinfluorescences,sqrtatypicalinfluorescences,totalinflorescence,sqrttotalinfluorescences,percentatypical,arsinpercentatypical,treatment #
0,2010,CALE,Hyslop,4,6,Roundup 0.1,1.0,1.000000,1.0,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010,CALE,Hyslop,12,7,Rdup/Bnvl 0.01,6.0,2.449490,2.0,0.141897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010,CALE,Hyslop,13,5,Roundup 0.01,8.0,2.828427,2.0,0.141897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,CALE,Hyslop,15,1,Carrier Control,3.0,1.732051,1.0,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,CALE,Hyslop,17,3,Banvel 0.01,0.0,0.000000,1.0,0.100167,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2299,2011,RAOC,Botany,370,8,Rdup+Bnvl 0.2,NaN,NaN,0.2,0.044736,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
2300,2011,RAOC,Botany,377,3,Banvel 0.1,NaN,NaN,0.5,0.070770,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
2301,2011,RAOC,Botany,379,4,Banvel 0.2,NaN,NaN,0.3,0.054800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
2302,2011,RAOC,Botany,380,2,No Spray,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2303,2011,RAOC,Botany,382,4,Banvel 0.2,NaN,NaN,0.2,0.044736,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0

### Part e
Many of the features that were brought into the appended dataframe were only present for one or a small number of the dataframes. Keep only the following features, which are present for most of the species:

In [34]:
cols_to_keep = ['year', 'species', 'site', 'plot', 'trt', 'treatment', 
                'pods', 'cover0', 'arsincover0', 'cover3', 'arsincover3', 
                'cover5', 'arsincover5']
combined_epa_data= combined_epa_data[cols_to_keep]
combined_epa_data

,year,species,site,plot,trt,treatment,pods,cover0,arsincover0,cover3,arsincover3,cover5,arsincover5
0,2010,CALE,Hyslop,4,6,Roundup 0.1,1.0,1.0,0.100167,2.00,0.141897,NaN,NaN
1,2010,CALE,Hyslop,12,7,Rdup/Bnvl 0.01,6.0,2.0,0.141897,1.00,0.100167,NaN,NaN
2,2010,CALE,Hyslop,13,5,Roundup 0.01,8.0,2.0,0.141897,2.00,0.141897,NaN,NaN
3,2010,CALE,Hyslop,15,1,Carrier Control,3.0,1.0,0.100167,1.00,0.100167,NaN,NaN
4,2010,CALE,Hyslop,17,3,Banvel 0.01,0.0,1.0,0.100167,2.00,0.141897,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2299,2011,RAOC,Botany,370,8,Rdup+Bnvl 0.2,NaN,0.2,0.044736,NaN,NaN,NaN,NaN
2300,2011,RAOC,Botany,377,3,Banvel 0.1,NaN,0.5,0.070770,0.30,0.054800,NaN,NaN
2301,2011,RAOC,Botany,379,4,Banvel 0.2,NaN,0.3,0.054800,0.20,0.044736,NaN,NaN
2302,2011,RAOC,Botany,380,2,No Spray,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2303,2011,RAOC,Botany,382,4,Banvel 0.2,NaN,0.2,0.044736,0.05,0.022363,NaN,NaN

Then save the resulting data in a separate CSV file. [8 points]

In [35]:
combined_epa_data.to_csv('combined_epa_data.csv', index=False)